using System.Diagnostics;
using System.Runtime.InteropServices;

namespace NxTestEmu;

delegate void StubDelegate();
delegate void DebugDelegate(ulong pc, string dasm);
unsafe delegate void LoadModuleDelegate(ulong loadBase, byte* data, int size);

delegate ulong ReadSrDelegate(uint op0, uint op1, uint crn, uint crm, uint op2);
delegate void WriteSrDelegate(uint op0, uint op1, uint crn, uint crm, uint op2, ulong value);
delegate ulong SetHeapSizeDelegate(ulong in_1, ref ulong out_1);
delegate ulong SetMemoryPermissionDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong SetMemoryAttributeDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong MapMemoryDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong UnmapMemoryDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong QueryMemoryDelegate(ulong in_0, ulong in_2, ref ulong out_1);
delegate void ExitProcessDelegate();
delegate ulong CreateThreadDelegate(ulong in_1, ulong in_2, ulong in_3, ulong in_4, ulong in_5, ref ulong out_1);
delegate ulong StartThreadDelegate(ulong in_0, ulong in_2, ulong in_3);
delegate void ExitThreadDelegate();
delegate void SleepThreadDelegate(ulong in_0);
delegate ulong GetThreadPriorityDelegate(ulong in_1, ref ulong out_1);
delegate ulong SetThreadPriorityDelegate(ulong in_0, ulong in_1);
delegate ulong GetThreadCoreMaskDelegate(ulong in_2, ref ulong out_1, ref ulong out_2);
delegate ulong SetThreadCoreMaskDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong GetCurrentProcessorNumberDelegate();
delegate ulong SignalEventDelegate(ulong in_0);
delegate ulong ClearEventDelegate(ulong in_0);
delegate ulong MapSharedMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong UnmapSharedMemoryDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong CreateTransferMemoryDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong CloseHandleDelegate(ulong in_0);
delegate ulong ResetSignalDelegate(ulong in_0);
delegate ulong WaitSynchronizationDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong CancelSynchronizationDelegate(ulong in_0);
delegate ulong ArbitrateLockDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong ArbitrateUnlockDelegate(ulong in_0);
delegate ulong WaitProcessWideKeyAtomicDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong SignalProcessWideKeyDelegate(ulong in_0, ulong in_1);
delegate ulong GetSystemTickDelegate();
delegate ulong ConnectToNamedPortDelegate(ulong in_1, ref ulong out_1);
delegate ulong SendSyncRequestLightDelegate(ulong in_0);
delegate ulong SendSyncRequestDelegate(ulong in_0);
delegate ulong SendSyncRequestWithUserBufferDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong SendAsyncRequestWithUserBufferDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong GetProcessIdDelegate(ulong in_1, ref ulong out_1);
delegate ulong GetThreadIdDelegate(ulong in_1, ref ulong out_1);
delegate ulong BreakDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong OutputDebugStringDelegate(ulong in_0, ulong in_1);
delegate void ReturnFromExceptionDelegate(ulong in_0);
delegate ulong GetInfoDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate void FlushEntireDataCacheDelegate();
delegate ulong FlushDataCacheDelegate(ulong in_0, ulong in_1);
delegate ulong MapPhysicalMemoryDelegate(ulong in_0, ulong in_1);
delegate ulong UnmapPhysicalMemoryDelegate(ulong in_0, ulong in_1);
delegate ulong GetDebugFutureThreadInfoDelegate(ulong in_3, ref ulong out_1, ref ulong out_2, ref ulong out_3, ref ulong out_4, ref ulong out_5, ref ulong out_6);
delegate ulong GetLastThreadInfoDelegate(ref ulong out_1, ref ulong out_2, ref ulong out_3, ref ulong out_4, ref ulong out_5, ref ulong out_6);
delegate ulong GetResourceLimitLimitValueDelegate(ulong in_1, ulong in_2, ref ulong out_1);
delegate ulong GetResourceLimitCurrentValueDelegate(ulong in_1, ulong in_2, ref ulong out_1);
delegate ulong SetThreadActivityDelegate(ulong in_0, ulong in_1);
delegate ulong GetThreadContext3Delegate(ulong in_0, ulong in_1);
delegate ulong WaitForAddressDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong SignalToAddressDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate void SynchronizePreemptionStateDelegate();
delegate ulong GetResourceLimitPeakValueDelegate(ulong in_1, ulong in_2, ref ulong out_1);
delegate void CreateIoPoolDelegate();
delegate void CreateIoRegionDelegate();
delegate ulong KernelDebugDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong ChangeKernelTraceStateDelegate(ulong in_0);
delegate ulong CreateSessionDelegate(ulong in_2, ulong in_3, ref ulong out_1, ref ulong out_2);
delegate ulong AcceptSessionDelegate(ulong in_1, ref ulong out_1);
delegate ulong ReplyAndReceiveLightDelegate(ulong in_0);
delegate ulong ReplyAndReceiveDelegate(ulong in_1, ulong in_2, ulong in_3, ulong in_4, ref ulong out_1);
delegate ulong ReplyAndReceiveWithUserBufferDelegate(ulong in_1, ulong in_2, ulong in_3, ulong in_4, ulong in_5, ulong in_6, ref ulong out_1);
delegate ulong CreateEventDelegate(ref ulong out_1, ref ulong out_2);
delegate void MapIoRegionDelegate();
delegate void UnmapIoRegionDelegate();
delegate ulong MapPhysicalMemoryUnsafeDelegate(ulong in_0, ulong in_1);
delegate ulong UnmapPhysicalMemoryUnsafeDelegate(ulong in_0, ulong in_1);
delegate ulong SetUnsafeLimitDelegate(ulong in_0);
delegate ulong CreateCodeMemoryDelegate(ulong in_1, ulong in_2, ref ulong out_1);
delegate ulong ControlCodeMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3, ulong in_4);
delegate void SleepSystemDelegate();
delegate ulong ReadWriteRegisterDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong SetProcessActivityDelegate(ulong in_0, ulong in_1);
delegate ulong CreateSharedMemoryDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong MapTransferMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong UnmapTransferMemoryDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong CreateInterruptEventDelegate(ulong in_1, ulong in_2, ref ulong out_1);
delegate ulong QueryPhysicalAddressDelegate(ulong in_1, ref ulong out_1, ref ulong out_2, ref ulong out_3);
delegate void QueryMemoryMappingDelegate();
delegate ulong CreateDeviceAddressSpaceDelegate(ulong in_1, ulong in_2, ref ulong out_1);
delegate ulong AttachDeviceAddressSpaceDelegate(ulong in_0, ulong in_1);
delegate ulong DetachDeviceAddressSpaceDelegate(ulong in_0, ulong in_1);
delegate ulong MapDeviceAddressSpaceByForceDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3, ulong in_4, ulong in_5);
delegate ulong MapDeviceAddressSpaceAlignedDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3, ulong in_4, ulong in_5);
delegate ulong MapDeviceAddressSpaceDelegate(ulong in_1, ulong in_2, ulong in_3, ulong in_4, ulong in_5, ulong in_6, ref ulong out_1);
delegate ulong UnmapDeviceAddressSpaceDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3, ulong in_4);
delegate ulong InvalidateProcessDataCacheDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong StoreProcessDataCacheDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong FlushProcessDataCacheDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong DebugActiveProcessDelegate(ulong in_1, ref ulong out_1);
delegate ulong BreakDebugProcessDelegate(ulong in_0);
delegate ulong TerminateDebugProcessDelegate(ulong in_0);
delegate ulong GetDebugEventDelegate(ulong in_0, ulong in_1);
delegate ulong ContinueDebugEventDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong GetProcessListDelegate(ulong in_1, ulong in_2, ref ulong out_1);
delegate ulong GetThreadListDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong GetDebugThreadContextDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong SetDebugThreadContextDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong QueryDebugProcessMemoryDelegate(ulong in_0, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong ReadDebugProcessMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong WriteDebugProcessMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong SetHardwareBreakPointDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong GetDebugThreadParamDelegate(ulong in_2, ulong in_3, ulong in_4, ref ulong out_1, ref ulong out_2);
delegate ulong GetSystemInfoDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong CreatePortDelegate(ulong in_2, ulong in_3, ulong in_4, ref ulong out_1, ref ulong out_2);
delegate ulong ManageNamedPortDelegate(ulong in_1, ulong in_2, ref ulong out_1);
delegate ulong ConnectToPortDelegate(ulong in_1, ref ulong out_1);
delegate ulong SetProcessMemoryPermissionDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong MapProcessMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong UnmapProcessMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong QueryProcessMemoryDelegate(ulong in_0, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong MapProcessCodeMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong UnmapProcessCodeMemoryDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong CreateProcessDelegate(ulong in_1, ulong in_2, ulong in_3, ref ulong out_1);
delegate ulong StartProcessDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3);
delegate ulong TerminateProcessDelegate(ulong in_0);
delegate ulong GetProcessInfoDelegate(ulong in_0, ulong in_1, ref ulong out_1);
delegate ulong CreateResourceLimitDelegate(ref ulong out_1);
delegate ulong SetResourceLimitLimitValueDelegate(ulong in_0, ulong in_1, ulong in_2);
delegate ulong CallSecureMonitorDelegate(ulong in_0, ulong in_1, ulong in_2, ulong in_3, ulong in_4, ulong in_5, ulong in_6, ulong in_7, ref ulong out_1, ref ulong out_2, ref ulong out_3, ref ulong out_4, ref ulong out_5, ref ulong out_6, ref ulong out_7);
delegate void SetMemoryAttribute2Delegate();
delegate void MapInsecurePhysicalMemoryDelegate();
delegate void UnmapInsecurePhysicalMemoryDelegate();

[StructLayout(LayoutKind.Sequential)]
public struct Callbacks() {
    public IntPtr debug = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("debug"));
    public IntPtr loadModule = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("loadModule"));
    public IntPtr readSr = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("readSr"));
    public IntPtr writeSr = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("writeSr"));
    public IntPtr svcSetHeapSize = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetHeapSize"));
    public IntPtr svcSetMemoryPermission = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetMemoryPermission"));
    public IntPtr svcSetMemoryAttribute = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetMemoryAttribute"));
    public IntPtr svcMapMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapMemory"));
    public IntPtr svcUnmapMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapMemory"));
    public IntPtr svcQueryMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcQueryMemory"));
    public IntPtr svcExitProcess = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcExitProcess"));
    public IntPtr svcCreateThread = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateThread"));
    public IntPtr svcStartThread = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcStartThread"));
    public IntPtr svcExitThread = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcExitThread"));
    public IntPtr svcSleepThread = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSleepThread"));
    public IntPtr svcGetThreadPriority = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetThreadPriority"));
    public IntPtr svcSetThreadPriority = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetThreadPriority"));
    public IntPtr svcGetThreadCoreMask = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetThreadCoreMask"));
    public IntPtr svcSetThreadCoreMask = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetThreadCoreMask"));
    public IntPtr svcGetCurrentProcessorNumber = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetCurrentProcessorNumber"));
    public IntPtr svcSignalEvent = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSignalEvent"));
    public IntPtr svcClearEvent = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcClearEvent"));
    public IntPtr svcMapSharedMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapSharedMemory"));
    public IntPtr svcUnmapSharedMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapSharedMemory"));
    public IntPtr svcCreateTransferMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateTransferMemory"));
    public IntPtr svcCloseHandle = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCloseHandle"));
    public IntPtr svcResetSignal = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcResetSignal"));
    public IntPtr svcWaitSynchronization = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcWaitSynchronization"));
    public IntPtr svcCancelSynchronization = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCancelSynchronization"));
    public IntPtr svcArbitrateLock = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcArbitrateLock"));
    public IntPtr svcArbitrateUnlock = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcArbitrateUnlock"));
    public IntPtr svcWaitProcessWideKeyAtomic = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcWaitProcessWideKeyAtomic"));
    public IntPtr svcSignalProcessWideKey = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSignalProcessWideKey"));
    public IntPtr svcGetSystemTick = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetSystemTick"));
    public IntPtr svcConnectToNamedPort = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcConnectToNamedPort"));
    public IntPtr svcSendSyncRequestLight = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSendSyncRequestLight"));
    public IntPtr svcSendSyncRequest = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSendSyncRequest"));
    public IntPtr svcSendSyncRequestWithUserBuffer = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSendSyncRequestWithUserBuffer"));
    public IntPtr svcSendAsyncRequestWithUserBuffer = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSendAsyncRequestWithUserBuffer"));
    public IntPtr svcGetProcessId = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetProcessId"));
    public IntPtr svcGetThreadId = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetThreadId"));
    public IntPtr svcBreak = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcBreak"));
    public IntPtr svcOutputDebugString = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcOutputDebugString"));
    public IntPtr svcReturnFromException = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcReturnFromException"));
    public IntPtr svcGetInfo = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetInfo"));
    public IntPtr svcFlushEntireDataCache = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcFlushEntireDataCache"));
    public IntPtr svcFlushDataCache = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcFlushDataCache"));
    public IntPtr svcMapPhysicalMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapPhysicalMemory"));
    public IntPtr svcUnmapPhysicalMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapPhysicalMemory"));
    public IntPtr svcGetDebugFutureThreadInfo = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetDebugFutureThreadInfo"));
    public IntPtr svcGetLastThreadInfo = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetLastThreadInfo"));
    public IntPtr svcGetResourceLimitLimitValue = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetResourceLimitLimitValue"));
    public IntPtr svcGetResourceLimitCurrentValue = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetResourceLimitCurrentValue"));
    public IntPtr svcSetThreadActivity = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetThreadActivity"));
    public IntPtr svcGetThreadContext3 = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetThreadContext3"));
    public IntPtr svcWaitForAddress = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcWaitForAddress"));
    public IntPtr svcSignalToAddress = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSignalToAddress"));
    public IntPtr svcSynchronizePreemptionState = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSynchronizePreemptionState"));
    public IntPtr svcGetResourceLimitPeakValue = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetResourceLimitPeakValue"));
    public IntPtr svcCreateIoPool = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateIoPool"));
    public IntPtr svcCreateIoRegion = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateIoRegion"));
    public IntPtr svcKernelDebug = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcKernelDebug"));
    public IntPtr svcChangeKernelTraceState = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcChangeKernelTraceState"));
    public IntPtr svcCreateSession = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateSession"));
    public IntPtr svcAcceptSession = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcAcceptSession"));
    public IntPtr svcReplyAndReceiveLight = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcReplyAndReceiveLight"));
    public IntPtr svcReplyAndReceive = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcReplyAndReceive"));
    public IntPtr svcReplyAndReceiveWithUserBuffer = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcReplyAndReceiveWithUserBuffer"));
    public IntPtr svcCreateEvent = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateEvent"));
    public IntPtr svcMapIoRegion = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapIoRegion"));
    public IntPtr svcUnmapIoRegion = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapIoRegion"));
    public IntPtr svcMapPhysicalMemoryUnsafe = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapPhysicalMemoryUnsafe"));
    public IntPtr svcUnmapPhysicalMemoryUnsafe = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapPhysicalMemoryUnsafe"));
    public IntPtr svcSetUnsafeLimit = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetUnsafeLimit"));
    public IntPtr svcCreateCodeMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateCodeMemory"));
    public IntPtr svcControlCodeMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcControlCodeMemory"));
    public IntPtr svcSleepSystem = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSleepSystem"));
    public IntPtr svcReadWriteRegister = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcReadWriteRegister"));
    public IntPtr svcSetProcessActivity = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetProcessActivity"));
    public IntPtr svcCreateSharedMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateSharedMemory"));
    public IntPtr svcMapTransferMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapTransferMemory"));
    public IntPtr svcUnmapTransferMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapTransferMemory"));
    public IntPtr svcCreateInterruptEvent = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateInterruptEvent"));
    public IntPtr svcQueryPhysicalAddress = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcQueryPhysicalAddress"));
    public IntPtr svcQueryMemoryMapping = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcQueryMemoryMapping"));
    public IntPtr svcCreateDeviceAddressSpace = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateDeviceAddressSpace"));
    public IntPtr svcAttachDeviceAddressSpace = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcAttachDeviceAddressSpace"));
    public IntPtr svcDetachDeviceAddressSpace = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcDetachDeviceAddressSpace"));
    public IntPtr svcMapDeviceAddressSpaceByForce = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapDeviceAddressSpaceByForce"));
    public IntPtr svcMapDeviceAddressSpaceAligned = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapDeviceAddressSpaceAligned"));
    public IntPtr svcMapDeviceAddressSpace = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapDeviceAddressSpace"));
    public IntPtr svcUnmapDeviceAddressSpace = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapDeviceAddressSpace"));
    public IntPtr svcInvalidateProcessDataCache = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcInvalidateProcessDataCache"));
    public IntPtr svcStoreProcessDataCache = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcStoreProcessDataCache"));
    public IntPtr svcFlushProcessDataCache = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcFlushProcessDataCache"));
    public IntPtr svcDebugActiveProcess = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcDebugActiveProcess"));
    public IntPtr svcBreakDebugProcess = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcBreakDebugProcess"));
    public IntPtr svcTerminateDebugProcess = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcTerminateDebugProcess"));
    public IntPtr svcGetDebugEvent = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetDebugEvent"));
    public IntPtr svcContinueDebugEvent = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcContinueDebugEvent"));
    public IntPtr svcGetProcessList = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetProcessList"));
    public IntPtr svcGetThreadList = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetThreadList"));
    public IntPtr svcGetDebugThreadContext = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetDebugThreadContext"));
    public IntPtr svcSetDebugThreadContext = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetDebugThreadContext"));
    public IntPtr svcQueryDebugProcessMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcQueryDebugProcessMemory"));
    public IntPtr svcReadDebugProcessMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcReadDebugProcessMemory"));
    public IntPtr svcWriteDebugProcessMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcWriteDebugProcessMemory"));
    public IntPtr svcSetHardwareBreakPoint = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetHardwareBreakPoint"));
    public IntPtr svcGetDebugThreadParam = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetDebugThreadParam"));
    public IntPtr svcGetSystemInfo = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetSystemInfo"));
    public IntPtr svcCreatePort = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreatePort"));
    public IntPtr svcManageNamedPort = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcManageNamedPort"));
    public IntPtr svcConnectToPort = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcConnectToPort"));
    public IntPtr svcSetProcessMemoryPermission = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetProcessMemoryPermission"));
    public IntPtr svcMapProcessMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapProcessMemory"));
    public IntPtr svcUnmapProcessMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapProcessMemory"));
    public IntPtr svcQueryProcessMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcQueryProcessMemory"));
    public IntPtr svcMapProcessCodeMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapProcessCodeMemory"));
    public IntPtr svcUnmapProcessCodeMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapProcessCodeMemory"));
    public IntPtr svcCreateProcess = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateProcess"));
    public IntPtr svcStartProcess = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcStartProcess"));
    public IntPtr svcTerminateProcess = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcTerminateProcess"));
    public IntPtr svcGetProcessInfo = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcGetProcessInfo"));
    public IntPtr svcCreateResourceLimit = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCreateResourceLimit"));
    public IntPtr svcSetResourceLimitLimitValue = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetResourceLimitLimitValue"));
    public IntPtr svcCallSecureMonitor = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcCallSecureMonitor"));
    public IntPtr svcSetMemoryAttribute2 = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcSetMemoryAttribute2"));
    public IntPtr svcMapInsecurePhysicalMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcMapInsecurePhysicalMemory"));
    public IntPtr svcUnmapInsecurePhysicalMemory = Marshal.GetFunctionPointerForDelegate<StubDelegate>(() => throw new NotImplementedException("svcUnmapInsecurePhysicalMemory"));
}