using ArchCompilerCore;
using Frontends.Aarch64;
using LibSharpRetro;
using static Backends.Rust.RustEmit;

namespace Backends.Rust;

// Rung-4 step ②: generate `recompiler.rs` for aarch64 — mask/match dispatch + per-insn
// bodies emitting Builder-trait calls. Rung-4's oracle = `cargo build` on the generated
// crate against rust/sharpretro-jit's Builder trait (typechecker = the gate).
//
// The walls-ladder: fire → throw-on-unhandled names the first missing head → add it →
// re-fire. Head-fill order = frequency (which head blocks most defs).

public static class Aarch64Scaffold {
    public static void RegisterAll() {
        ScalarMathEmit.Register();
        ControlFlowEmit.Register();
        LogicEmit.Register();
        VectorMathEmit.Register();
        Aarch64Emit.Register();
    }

    public static void BuildRecompiler(List<Aarch64Def> defs, string outPath) {
        Context = ContextTypes.Recompiler;

        var c = new CodeBuilder();
        c += "// GENERATED by ArchCompiler Backends/Rust from aarch64.isa — do not hand-edit.";
        c += "#![allow(unused_variables, unused_parens, non_snake_case, unreachable_code, unused_labels, unused_unsafe)]";
        c += "use sharpretro_jit::{Builder, IlType, RegFile, IntrinsicId, RoundMode};";
        c += "";
        c += "// Compiletime helpers (aarch64 bitmask-immediate decode etc). These are pure fns of";
        c += "// the encoded-immediate bits — should fold at generated-code const-eval. Rung-4a";
        c += "// declares them extern; rung-4b: ArchCompilerCore's compiletime-eval leg folds them";
        c += "// to constants pre-emit (the .isa's `literal` heads = the fold-hint).";
        // Rung-4a stubs (fold to constants at rung-4b via ArchCompilerCore's ct-eval).
        c += "fn aarch64_wmask(_n: u32, _imms: u32, _immr: u32, _imm: u32, _m: u32) -> u64 { todo!() }";
        c += "fn aarch64_tmask(_n: u32, _imms: u32, _immr: u32, _imm: u32, _m: u32) -> u64 { todo!() }";
        c += "fn aarch64_replicate(_bits: u64, _w: u32, _c: u32) -> u64 { todo!() }";
        c += "";
        c += "// Register-file ids (aarch64). The frontend declares these; the tier is opaque to them.";
        c += "pub const GPR: RegFile = RegFile(0);";
        c += "pub const VEC: RegFile = RegFile(1);";
        c += "pub const NZCV: RegFile = RegFile(2);";
        c += "pub const SR: RegFile = RegFile(3);";
        c += "";
        c += "/// Recompile one aarch64 instruction at `pc` into `b`. Returns whether decoded.";
        c += "pub fn recompile_one<B: Builder>(bd: &mut B, insn: u32, pc: u64) -> bool {";
        c++;

        var (emitted, blocked) = (0, new Dictionary<string, int>());
        foreach(var def in defs) {
            NextLabel = null;
            c += $"/* {def.Name} */";
            c += $"if (insn & 0x{def.Mask:X08}) == 0x{def.Match:X08} {{ 'decode: {{";
            c++;
            GenerateFields(c, def);
            // Buffer decode+eval into a scratch CodeBuilder at indent-0 — a throw mid-emit
            // leaves partial `{`/indent debris otherwise. On success, splice each buffered
            // line into `c` (which re-indents per its own operator+).
            var body = new CodeBuilder();
            RtReset(body);  // temps from Rt() write into the same buffer as statements —
                            // eval order (children first via recursion) → temps land above
                            // the statement that consumes them.
            try {
                GenerateStatement(body, def.Decode);
                GenerateStatement(body, def.Eval);
                foreach(var line in body.Code.Split('\n', StringSplitOptions.RemoveEmptyEntries))
                    c += line.TrimStart('\t');
                c += "return true;";
                emitted++;
            } catch(Exception e) when(e is NotImplementedException or NotSupportedException
                                            or InvalidCastException or ArgumentOutOfRangeException) {
                var head = e.Message.Contains('\'')
                    ? e.Message.Split('\'')[1] : e.Message;
                blocked[head] = blocked.GetValueOrDefault(head) + 1;
                c += $"bd.unimplemented(\"{def.Name}\");  // BLOCKED: {head}";
                c += "return true;";
            }
            c--;
            c += "} }";
        }

        c += "false";
        c--;
        c += "}";

        File.WriteAllText(outPath, c.Code);

        // The walls-ladder census: which head blocks most defs?
        Console.Error.WriteLine($"[rust-emit: {emitted}/{defs.Count} defs emitted]");
        foreach(var (head, n) in blocked.OrderByDescending(kv => kv.Value))
            Console.Error.WriteLine($"  BLOCKED {n,3}× by head '{head}'");
    }

    static void GenerateFields(CodeBuilder c, Aarch64Def def) {
        foreach(var (key, (bits, shift)) in def.Fields)
            c += $"let {RustEmit.SafeIdent(key)} = (insn >> {shift}) & 0x{(1 << bits) - 1:X};";
    }
}
