using ArchCompilerCore;
using Frontends.Aarch64;
using LibSharpRetro;
using static Backends.Rust.RustEmit;

namespace Backends.Rust;

// Rung-4 step ②: generate `recompiler.rs` for aarch64 — mask/match dispatch + per-insn
// bodies emitting Builder-trait calls. Rung-4's oracle = `cargo build` on the generated
// crate against rust/sharpretro-jit's Builder trait (typechecker = the gate).
//
// The walls-ladder: fire → throw-on-unhandled names the first missing head → add it →
// re-fire. Head-fill order = frequency (which head blocks most defs).

public static class Aarch64Scaffold {
    public static void RegisterAll() {
        ScalarMathEmit.Register();
        ControlFlowEmit.Register();
        LogicEmit.Register();
        VectorMathEmit.Register();
        Aarch64Emit.Register();
    }

    public static void BuildRecompiler(List<Aarch64Def> defs, string outPath) {
        Context = ContextTypes.Recompiler;

        var c = new CodeBuilder();
        c += "// GENERATED by ArchCompiler Backends/Rust from aarch64.isa — do not hand-edit.";
        c += "#![allow(unused_variables, unused_parens, non_snake_case, unreachable_code, unused_labels, unused_unsafe, unused_mut, unused_assignments)]";
        c += "use sharpretro_jit::{Builder, IlType, RegFile, IntrinsicId, RoundMode};";
        c += "";
        c += "// Compiletime helpers (aarch64 bitmask-immediate decode etc). These are pure fns of";
        c += "// the encoded-immediate bits — should fold at generated-code const-eval. Rung-4a";
        c += "// declares them extern; rung-4b: ArchCompilerCore's compiletime-eval leg folds them";
        c += "// to constants pre-emit (the .isa's `literal` heads = the fold-hint).";
        // aarch64 bitmask-immediate decode. Ported verbatim from Aarch64Common.Common.
        // .isa arg-order is (n imms immr immediate m); C# fn takes (n imms immr m immediate)
        // and the legacy emit swaps [4]/[5] — this signature matches the .isa order directly.
        // BailoutException → returns None; the .isa's `requires` should have caught it, but
        // if it didn't (over-permissive), the caller will `unreachable!()` on the None.
        c += @"fn ones(bits: u32) -> u64 { if bits >= 64 { u64::MAX } else { (1u64 << bits) - 1 } }
fn highest_set_bit(v: u64, bits: u32) -> i32 {
    for i in (0..bits as i32).rev() { if (v >> i) & 1 != 0 { return i; } }
    -1
}
fn roll_right(v: u64, size: u32, rot: u32) -> u64 {
    if rot == 0 { return v & ones(size); }
    ((v << (size - rot)) | (v >> rot)) & ones(size)
}
fn replicate_(v: u64, esize: u32, m: u32) -> u64 {
    // esize can be 64 (when N=1, len=6) → u64<<64 panics in Rust debug (C# tolerates →0).
    if esize >= 64 { return v & ones(64); }
    let times = m / esize; let mut r = 0u64;
    for _ in 0..times { r = (r << esize) | (v & ones(esize)); }
    r
}
fn make_masks(n: u32, imms: u32, immr: u32, m: u32, immediate: bool) -> Option<(u64, u64)> {
    let len = highest_set_bit(((n << 6) | (imms ^ 0b111111)) as u64, 7);
    if !(len > 0 && m >= (1u32 << len)) { return None; }
    let levels = ones(len as u32) & 0x3F;
    if immediate && (imms as u64 & levels) == levels { return None; }
    let s = imms as u64 & levels; let r = immr as u64 & levels;
    let diff = (s.wrapping_sub(r)) & 0x3F;
    let esize = 1u32 << len;
    let d = diff & ones(len as u32);
    let welem = ones((s + 1) as u32) & ones(esize);
    let telem = ones((d + 1) as u32) & ones(esize);
    let wmask = replicate_(roll_right(welem, esize, r as u32), esize, m);
    let tmask = replicate_(telem, esize, m);
    Some((wmask, tmask))
}
fn aarch64_wmask(n: u32, imms: u32, immr: u32, immediate: u32, m: u32) -> u64 {
    // None = an UNALLOCATED bitmask-immediate encoding (no valid len for imms) --
    // architecturally a decode-reject, but wmask is an EVAL-time helper with no path
    // back to 'decode. Named panic so the fuzz census reads the class honestly
    // (was anonymous unreachable!() -- indistinguishable from a match-default bug).
    make_masks(n, imms, immr, m, immediate != 0).map(|(w,_)| w)
        .unwrap_or_else(|| panic!("UNALLOCATED bitmask-immediate (n={n} imms={imms} immr={immr})"))
}
fn aarch64_tmask(n: u32, imms: u32, immr: u32, immediate: u32, m: u32) -> u64 {
    make_masks(n, imms, immr, m, immediate != 0).map(|(_,t)| t)
        .unwrap_or_else(|| panic!("UNALLOCATED bitmask-immediate (n={n} imms={imms} immr={immr})"))
}
fn aarch64_replicate(bits: u64, w: u32, c: u32) -> u64 { replicate_(bits, w, w * c) }
";
        c += "";
        c += "// Register-file ids (aarch64). The frontend declares these; the tier is opaque to them.";
        c += "pub const GPR: RegFile = RegFile(0);";
        c += "pub const VEC: RegFile = RegFile(1);";
        c += "pub const NZCV: RegFile = RegFile(2);";
        c += "pub const SR: RegFile = RegFile(3);";
        c += "";
        c += "/// Recompile one aarch64 instruction at `pc` into `b`. Returns whether decoded.";
        c += "pub fn recompile_one<B: Builder>(bd: &mut B, insn: u32, pc: u64) -> bool {";
        c++;

        var (emitted, blocked) = (0, new Dictionary<string, int>());
        foreach(var def in defs) {
            NextLabel = null;
            c += $"/* {def.Name} */";
            c += $"if (insn & 0x{def.Mask:X08}) == 0x{def.Match:X08} {{ 'decode: {{";
            c++;
            GenerateFields(c, def);
            // Buffer decode+eval into a scratch CodeBuilder at indent-0 — a throw mid-emit
            // leaves partial `{`/indent debris otherwise. On success, splice each buffered
            // line into `c` (which re-indents per its own operator+).
            var body = new CodeBuilder();
            RtReset(body);  // temps from Rt() write into the same buffer as statements —
                            // eval order (children first via recursion) → temps land above
                            // the statement that consumes them.
            try {
                GenerateStatement(body, def.Decode);
                GenerateStatement(body, def.Eval);
                foreach(var line in body.Code.Split('\n', StringSplitOptions.RemoveEmptyEntries))
                    c += line.TrimStart('\t');
                c += "return true;";
                emitted++;
            } catch(Exception e) when(e is NotImplementedException or NotSupportedException
                                            or InvalidCastException or ArgumentOutOfRangeException) {
                var head = e.Message.Contains('\'')
                    ? e.Message.Split('\'')[1] : e.Message;
                blocked[head] = blocked.GetValueOrDefault(head) + 1;
                c += $"bd.unimplemented(\"{def.Name}\");  // BLOCKED: {head}";
                c += "return true;";
            }
            c--;
            c += "} }";
        }

        c += "false";
        c--;
        c += "}";

        File.WriteAllText(outPath, c.Code);

        // The walls-ladder census: which head blocks most defs?
        Console.Error.WriteLine($"[rust-emit: {emitted}/{defs.Count} defs emitted]");
        foreach(var (head, n) in blocked.OrderByDescending(kv => kv.Value))
            Console.Error.WriteLine($"  BLOCKED {n,3}× by head '{head}'");
    }

    static void GenerateFields(CodeBuilder c, Aarch64Def def) {
        foreach(var (key, (bits, shift)) in def.Fields)
            c += $"let {RustEmit.SafeIdent(key)} = (insn >> {shift}) & 0x{(1 << bits) - 1:X};";
    }
}
