using System.Text;
using CoreArchCompiler;

namespace XFusionGenerator;

/// <summary>
/// Emits XFusionCpu/Generated/Disassembler.cs. Dispatch is over (map, opcode, ModRM.reg
/// for /N-extended rows); operand text comes from the shared runtime (Decode.GprName /
/// MemOperandString) driven by each encoding's OperandSpec list. The dasm template
/// string from the .isa binds $param names positionally to the encoding's specs.
/// </summary>
public static class DisassemblerGenerator {
	public static string Generate(List<XFusionDef> defs) {
		var sb = new StringBuilder();
		sb.AppendLine("// GENERATED by XFusionGenerator — do not edit.");
		sb.AppendLine("namespace XFusionCpu;");
		sb.AppendLine();
		sb.AppendLine("public static partial class Disassembler {");
		sb.AppendLine($"\tpublic const int EncodingCount = {defs.Count};");
		sb.AppendLine();
		sb.AppendLine("\t/// Returns (text, length) or (null, 0) if undecodable.");
		sb.AppendLine("\tpublic static (string Text, int Length) Disassemble(ReadOnlySpan<byte> code, ulong pc, XMode mode) {");
		sb.AppendLine("\t\tvar pLen = Decode.ScanPrefixes(code, mode, out var p);");
		sb.AppendLine("\t\tvar i = pLen;");
		sb.AppendLine("\t\tif(i >= code.Length) return (null, 0);");
		sb.AppendLine("\t\tvar op = code[i++];");
		sb.AppendLine("\t\tvar map = OpcodeMap.OneByte;");
		sb.AppendLine("\t\tif(op == 0x0F) {");
		sb.AppendLine("\t\t\tif(i >= code.Length) return (null, 0);");
		sb.AppendLine("\t\t\top = code[i++];");
		sb.AppendLine("\t\t\tmap = OpcodeMap.TwoByte0F;");
		sb.AppendLine("\t\t\tif(op == 0x38) { if(i >= code.Length) return (null, 0); op = code[i++]; map = OpcodeMap.ThreeByte0F38; }");
		sb.AppendLine("\t\t\telse if(op == 0x3A) { if(i >= code.Length) return (null, 0); op = code[i++]; map = OpcodeMap.ThreeByte0F3A; }");
		sb.AppendLine("\t\t}");
		sb.AppendLine();

		// Group: (map, opcode) -> defs (multiple only via /N extensions)
		// +r defs occupy 8 consecutive opcodes — expand for grouping/dispatch.
		var dispatchRows = defs.SelectMany(d => d.PlusR
			? Enumerable.Range(0, 8).Select(r => (Op: (byte) (d.Opcode + r), Def: d))
			: [(Op: d.Opcode, Def: d)]);
		var groups = dispatchRows.GroupBy(x => (x.Def.Map, x.Op)).OrderBy(g => g.Key.Map).ThenBy(g => g.Key.Op);
		sb.AppendLine("\t\tswitch(map, op) {");
		foreach(var g in groups) {
			var mapName = g.Key.Map.ToString();
			sb.AppendLine($"\t\t\tcase (OpcodeMap.{mapName}, 0x{g.Key.Op:X2}): {{");
			// Mandatory-prefix rows dispatch first (F3 90 = pause, not rep nop; SSE later).
			// The matched prefix is CONSUMED — cleared so it doesn't render as rep/data16.
			foreach(var pd in g.Select(x => x.Def).Where(d => d.MandatoryPrefix != null)) {
				var cond = pd.MandatoryPrefix switch {
					"rep" => "p.Rep", "repnz" => "p.RepNz", "opsize" => "p.OpSize",
					_ => throw new NotSupportedException(pd.MandatoryPrefix)
				};
				var clear = pd.MandatoryPrefix switch {
					"rep" => "p.Rep = false;", "repnz" => "p.RepNz = false;", "opsize" => "p.OpSize = false;",
					_ => null
				};
				sb.AppendLine($"\t\t\t\tif({cond}) {{");
				sb.AppendLine($"\t\t\t\t\t{clear}");
				EmitDefBody(sb, pd, "\t\t\t\t\t");
				sb.AppendLine("\t\t\t\t}");
			}
			var byExt = g.Select(x => x.Def).Where(d => d.MandatoryPrefix == null).ToList();
			if(byExt.Count == 0) { sb.AppendLine("\t\t\t\treturn (null, 0);"); sb.AppendLine("\t\t\t}"); continue; }
			if(byExt.Count > 1 || byExt[0].RegExtension >= 0) {
				// need ModRM.reg to disambiguate; all rows in a /N group carry ModRM
				sb.AppendLine("\t\t\t\tif(i >= code.Length) return (null, 0);");
				sb.AppendLine("\t\t\t\tvar regField = (code[i] >> 3) & 7;");
				sb.AppendLine("\t\t\t\tswitch(regField) {");
				foreach(var d in byExt.OrderBy(x => x.RegExtension)) {
					if(d.RegExtension < 0)
						throw new NotSupportedException($"(map,opcode) collision without /N: {d.Name}");
					sb.AppendLine($"\t\t\t\t\tcase {d.RegExtension}: {{");
					EmitDefBody(sb, d, "\t\t\t\t\t\t");
					sb.AppendLine("\t\t\t\t\t}");
				}
				sb.AppendLine("\t\t\t\t\tdefault: return (null, 0);");
				sb.AppendLine("\t\t\t\t}");
			} else
				EmitDefBody(sb, byExt[0], "\t\t\t\t");
			sb.AppendLine("\t\t\t}");
		}
		sb.AppendLine("\t\t\tdefault: return (null, 0);");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine("}");
		return sb.ToString();
	}

	static void EmitDefBody(StringBuilder sb, XFusionDef def, string ind) {
		// Decode phase: ModRM if needed, then operand exprs in spec order.
		if(def.NeedsModRm) {
			sb.AppendLine($"{ind}if(i >= code.Length) return (null, 0);");
			sb.AppendLine($"{ind}i += Decode.ReadModRm(code[i..], mode, in p, out var m);");
			var memOnly = def.Operands.Any(o => o.MemOnly);
			if(memOnly) sb.AppendLine($"{ind}if(m.IsReg) return (null, 0);");
		}

		var opTexts = new List<string>();
		foreach(var spec in def.Operands)
			opTexts.Add(EmitOperand(sb, def, spec, ind));

		// Format: template dasm string with $param -> operand text, positionally.
		// lock/rep prefixes render before the mnemonic (XED convention). A 0x66 on a
		// zero-operand insn has nothing to absorb it — XED renders it as 'data16 ' (66 90).
		var fmt = RenderDasm(def, opTexts);
		var data16 = def.Operands.Count == 0 ? "(p.OpSize ? \"data16 \" : \"\") + " : "";
		sb.AppendLine($"{ind}return ({data16}Decode.MnemonicPrefix(in p) + {fmt}, i);");
	}

	/// Emits decode statements for one operand; returns the C# expression producing its text.
	static string EmitOperand(StringBuilder sb, XFusionDef def, OperandSpec spec, string ind) {
		var vw = def.D64 ? "p.VWidthD64(mode)" : "p.VWidth(mode)";
		string VWidthExpr() => vw;
		string WidthExpr() => spec.Width switch {
			WCode.b => "8",
			WCode.w => "16",
			WCode.v => vw,
			WCode.z => "p.ZWidth(mode)",
			WCode.d => "32",
			WCode.q => "64",
			_ => throw new NotSupportedException($"width {spec.Width} for {spec.Text}")
		};

		switch(spec.Class) {
			case OpClass.ModRmRm when spec.MemOnly:
				// address-only operand (LEA): no size qualifier — XED renders bare 'ptr [...]'
				return $"Decode.MemOperandString(in m, in p, mode, 0, pc + (ulong)i)";
			case OpClass.ModRmRm:
				return $"(m.IsReg ? Decode.GprName(m.Rm, {WidthExpr()}, p.Rex != 0) : Decode.MemOperandString(in m, in p, mode, {WidthExpr()}, pc + (ulong)i))";
			case OpClass.ModRmReg:
				return $"Decode.GprName(m.Reg, {WidthExpr()}, p.Rex != 0)";
			case OpClass.ModRmSeg:
				return "Decode.SegRegName(m.Reg)";
			case OpClass.FixedReg when spec.SegName != null:
				return $"\"{spec.SegName.ToLowerInvariant()}\"";
			case OpClass.FixedReg when spec.FixedRegByte:
				return $"Decode.GprName({spec.FixedRegIndex}, 8, p.Rex != 0)";
			case OpClass.FixedReg when spec.FixedRegVSized:
				return $"Decode.GprName({spec.FixedRegIndex}, p.VWidth(mode), p.Rex != 0)";
			case OpClass.FixedReg:
				return $"Decode.GprName({spec.FixedRegIndex}, 16, false)";
			case OpClass.FixedInt:
				return $"\"0x{spec.FixedValue:x}\"";
			case OpClass.OpcodeReg: {
				var w = spec.Width == WCode.b ? "8" : VWidthExpr();
				return $"Decode.GprName((op & 7) | (p.RexB ? 8 : 0), {w}, p.Rex != 0)";
			}
			case OpClass.Imm: {
				var v = $"imm_{spec.Text.Replace("-", "_")}";
				// z-imms fetch 16/32 but the VALUE is sign-extended to the v-sized destination
				// (SDM: imm32 sign-extended in 64-bit ops). Render masked to destination width
				// (XED: 83 C0 FB = add eax, 0xfffffffb; 48 C7 C0 FF.. = mov rax, 0xffffffffffffffff).
				var sx = spec.SignExtended || spec.Width == WCode.z;
				var destW = spec.SignExtended || spec.Width == WCode.z ? VWidthExpr() : WidthExpr();
				sb.AppendLine($"{ind}var {v} = Decode.MaskToWidth(Decode.ReadImm(code, ref i, {WidthExpr()}, {(sx ? "true" : "false")}), {destW});");
				return $"$\"0x{{{v}:x}}\"";
			}
			case OpClass.RelBranch: {
				var v = $"rel_{spec.Text}";
				sb.AppendLine($"{ind}var {v} = Decode.ReadImm(code, ref i, {WidthExpr()}, true);");
				return $"$\"0x{{pc + (ulong)i + (ulong){v}:x}}\"";
			}
			case OpClass.MemOffset: {
				var v = $"moffs_{spec.Text}";
				sb.AppendLine($"{ind}var {v} = Decode.ReadImm(code, ref i, p.AWidth(mode), false);");
				return $"$\"[0x{{{v}:x}}]\"";
			}
			default:
				throw new NotSupportedException($"operand class {spec.Class} ({spec.Text})");
		}
	}

	/// dasm template: "add $lval, $rval" — parse the PTree (string-concat of PString +
	/// PName segments per ListParser.ParseString) into a C# interpolated string.
	static string RenderDasm(XFusionDef def, List<string> opTexts) {
		string Bind(string pname) {
			var idx = def.ParamNames.IndexOf(pname);
			if(idx < 0) throw new NotSupportedException($"dasm of {def.Mnemonic} references ${pname}, not a template param");
			return opTexts[idx];
		}

		// $(wname n16 n32 n64): mnemonic selected by effective operand width (98/99 class).
		string TryWname(PTree t) {
			if(t is PList wl && wl.Count == 4 && wl[0] is PName("wname")
				&& wl[1] is PName(var n16) && wl[2] is PName(var n32) && wl[3] is PName(var n64))
				return $"(p.VWidth(mode) switch {{ 16 => \"{n16}\", 32 => \"{n32}\", _ => \"{n64}\" }})";
			return null;
		}

		switch(def.Dasm) {
			case PString { String: var s }:
				return $"\"{s}\"";
			case var t when TryWname(t) != null:
				return TryWname(t);
			case PName(var n):  // whole dasm is one $param (unusual but legal)
				return Bind(n);
			case PList l when l.Count > 0 && l[0] is PName("string-concat"): {
				var sb = new StringBuilder("$\"");
				foreach(var seg in l.Skip(1))
					switch(seg) {
						case PString { String: var s }: sb.Append(s.Replace("\"", "\\\"")); break;
						case PName(var n): sb.Append("{").Append(Bind(n)).Append("}"); break;
						default: throw new NotSupportedException($"dasm segment {seg} in {def.Mnemonic}");
					}
				sb.Append('"');
				return sb.ToString();
			}
			default:
				throw new NotSupportedException($"dasm shape for {def.Mnemonic}: {def.Dasm}");
		}
	}
}
