using System.Text;
using CoreArchCompiler;

namespace XFusionGenerator;

/// <summary>
/// Emits XFusionCpu/Generated/Disassembler.cs. Dispatch is over (map, opcode, ModRM.reg
/// for /N-extended rows); operand text comes from the shared runtime (Decode.GprName /
/// MemOperandString) driven by each encoding's OperandSpec list. The dasm template
/// string from the .isa binds $param names positionally to the encoding's specs.
/// </summary>
public static class DisassemblerGenerator {
	public static string Generate(List<XFusionDef> defs) {
		var sb = new StringBuilder();
		sb.AppendLine("// GENERATED by XFusionGenerator — do not edit.");
		sb.AppendLine("namespace XFusionCpu;");
		sb.AppendLine();
		sb.AppendLine("public static partial class Disassembler {");
		sb.AppendLine($"\tpublic const int EncodingCount = {defs.Count};");
		sb.AppendLine();
		sb.AppendLine("\t/// Returns (text, length) or (null, 0) if undecodable.");
		sb.AppendLine("\tpublic static (string Text, int Length) Disassemble(ReadOnlySpan<byte> code, ulong pc, XMode mode) {");
		sb.AppendLine("\t\tvar pLen = Decode.ScanPrefixes(code, mode, out var p);");
		sb.AppendLine("\t\tvar i = pLen;");
		sb.AppendLine("\t\tif(i >= code.Length) return (null, 0);");
		sb.AppendLine("\t\tvar op = code[i++];");
		sb.AppendLine("\t\tvar map = OpcodeMap.OneByte;");
		sb.AppendLine("\t\tif(p.VexValid) {");
		sb.AppendLine("\t\t\t// VEX carries the map — the opcode byte after the prefix is bare (no 0F escape)");
		sb.AppendLine("\t\t\tmap = p.VexMap switch { 1 => OpcodeMap.TwoByte0F, 2 => OpcodeMap.ThreeByte0F38, 3 => OpcodeMap.ThreeByte0F3A, _ => (OpcodeMap) 255 };");
		sb.AppendLine("\t\t\tif(map == (OpcodeMap) 255) return (null, 0);");
		sb.AppendLine("\t\t} else if(op == 0x0F) {");
		sb.AppendLine("\t\t\tif(i >= code.Length) return (null, 0);");
		sb.AppendLine("\t\t\top = code[i++];");
		sb.AppendLine("\t\t\tmap = OpcodeMap.TwoByte0F;");
		sb.AppendLine("\t\t\tif(op == 0x38) { if(i >= code.Length) return (null, 0); op = code[i++]; map = OpcodeMap.ThreeByte0F38; }");
		sb.AppendLine("\t\t\telse if(op == 0x3A) { if(i >= code.Length) return (null, 0); op = code[i++]; map = OpcodeMap.ThreeByte0F3A; }");
		sb.AppendLine("\t\t}");
		sb.AppendLine();

		// Group: (map, opcode) -> defs (multiple only via /N extensions)
		// +r defs occupy 8 consecutive opcodes — expand for grouping/dispatch.
		// An exact-opcode def SHADOWS a +r member at the same (map, opcode): 0x90 NOP
		// wins over XCHG (0x90 +r); 0x91-97 remain xchg. (90 IS xchg eax,eax — the
		// architectural alias; XED renders nop.)
		var exact = defs.Where(d => !d.PlusR).Select(d => (d.Map, d.Opcode)).ToHashSet();
		var dispatchRows = defs.SelectMany(d => d.PlusR
			? Enumerable.Range(0, 8).Select(r => (Op: (byte) (d.Opcode + r), Def: d))
				.Where(x => !exact.Contains((d.Map, x.Op)))
			: [(Op: d.Opcode, Def: d)]);
		var groups = dispatchRows.GroupBy(x => (x.Def.Map, x.Op)).OrderBy(g => g.Key.Map).ThenBy(g => g.Key.Op);
		sb.AppendLine("\t\tswitch(map, op) {");
		foreach(var g in groups) {
			var mapName = g.Key.Map.ToString();
			sb.AppendLine($"\t\t\tcase (OpcodeMap.{mapName}, 0x{g.Key.Op:X2}): {{");
			// VEX rows dispatch first, under p.VexValid (pp is folded into OpSize/Rep/RepNz
			// by the scanner, so the same prefix conditions discriminate). Legacy rows
			// implicitly reject VEX via the else-order + the vexGuard below.
			var vexRows = g.Select(x => x.Def).Where(d => d.Vex != VexMode.None).ToList();
			if(vexRows.Count > 0) {
				sb.AppendLine("\t\t\t\tif(p.VexValid) {");
				foreach(var vd in vexRows) {
					var conds = new List<string>();
					conds.Add(vd.Evex ? "p.EvexValid" : "!p.EvexValid");
					conds.Add(vd.MandatoryPrefix switch {
						"rep" => "p.Rep", "repnz" => "p.RepNz", "opsize" => "p.OpSize",
						null => "!p.OpSize && !p.Rep && !p.RepNz",
						_ => throw new NotSupportedException(vd.MandatoryPrefix)
					});
					if(vd.VexW is not null) conds.Add(vd.VexW.Value ? "p.RexW" : "!p.RexW");
					if(vd.Vex == VexMode.TwoSrc) conds.Add("p.VexVvvv == 0");  // #UD otherwise
					sb.AppendLine($"\t\t\t\t\tif({string.Join(" && ", conds)}) {{");
					EmitDefBody(sb, vd, "\t\t\t\t\t\t");
					sb.AppendLine("\t\t\t\t\t}");
				}
				sb.AppendLine("\t\t\t\t\treturn (null, 0);");
				sb.AppendLine("\t\t\t\t}");
			}
			sb.AppendLine("\t\t\t\tif(p.VexValid) return (null, 0);  // no VEX row here");
			// Mandatory-prefix rows dispatch next (F3 90 = pause, not rep nop).
			// The matched prefix is CONSUMED — cleared so it doesn't render as rep/data16.
			foreach(var pg in g.Select(x => x.Def).Where(d => d.MandatoryPrefix != null && d.Vex == VexMode.None).GroupBy(d => d.MandatoryPrefix)) {
				var cond = pg.Key switch {
					"rep" => "p.Rep", "repnz" => "p.RepNz", "opsize" => "p.OpSize",
					_ => throw new NotSupportedException(pg.Key)
				};
				var clear = pg.Key switch {
					"rep" => "p.Rep = false;", "repnz" => "p.RepNz = false;", "opsize" => "p.OpSize = false;",
					_ => null
				};
				sb.AppendLine($"\t\t\t\tif({cond}) {{");
				sb.AppendLine($"\t\t\t\t\t{clear}");
				var pdefs = pg.ToList();
				if(pdefs.Count > 1 || pdefs[0].RegExtension >= 0) {
					// /N-discriminated within this prefix (opsize 0F 73 /2 /3 /6 /7 class)
					sb.AppendLine("\t\t\t\t\tif(i >= code.Length) return (null, 0);");
					sb.AppendLine($"\t\t\t\t\tswitch((code[i] >> 3) & 7) {{");
					foreach(var pd in pdefs.OrderBy(x => x.RegExtension)) {
						if(pd.RegExtension < 0)
							throw new NotSupportedException($"prefix-group (map,opcode) collision without /N: {pd.Name}");
						sb.AppendLine($"\t\t\t\t\t\tcase {pd.RegExtension}: {{");
						EmitDefBody(sb, pd, "\t\t\t\t\t\t\t");
						sb.AppendLine("\t\t\t\t\t\t}");
					}
					sb.AppendLine("\t\t\t\t\t\tdefault: return (null, 0);");
					sb.AppendLine("\t\t\t\t\t}");
				} else
					EmitDefBody(sb, pdefs[0], "\t\t\t\t\t");
				sb.AppendLine("\t\t\t\t}");
			}
			var byExt = g.Select(x => x.Def).Where(d => d.MandatoryPrefix == null && d.Vex == VexMode.None).ToList();
			if(byExt.Count == 0) { sb.AppendLine("\t\t\t\treturn (null, 0);"); sb.AppendLine("\t\t\t}"); continue; }
			// Vector space (any V/W/U/P/Q operand in the group) is uniformly prefix-
			// discriminated: 66/F3/F2 ALWAYS select a different instruction there. The
			// bare row must REJECT unclaimed prefixes — an unimplemented 66-sibling has
			// to undecode, not misdecode as the ps form (census: movapd read as movaps).
			var isVectorGroup = g.Select(x => x.Def).Any(d => d.Operands.Any(o =>
				o.Class is OpClass.XmmReg or OpClass.XmmRm or OpClass.XmmRmReg or OpClass.MmxReg or OpClass.MmxRm));
			if(isVectorGroup) {
				var claimed = g.Select(x => x.Def.MandatoryPrefix).Where(x => x != null).ToHashSet();
				var rejects = new List<string>();
				if(!claimed.Contains("opsize")) rejects.Add("p.OpSize");
				if(!claimed.Contains("rep")) rejects.Add("p.Rep");
				if(!claimed.Contains("repnz")) rejects.Add("p.RepNz");
				if(rejects.Count > 0)
					sb.AppendLine($"\t\t\t\tif({string.Join(" || ", rejects)}) return (null, 0);");
			}
			// mod-field discrimination (0F 12: movhlps mod==11 / movlps mem): a RegOnly
			// (U*-operand) def and a MemOnly def can share (map, opcode) without /N.
			if(byExt.Count == 2 && byExt.All(d => d.RegExtension < 0)) {
				var regForm = byExt.FirstOrDefault(d => d.Operands.Any(o => o.Class == OpClass.XmmRmReg));
				var memForm = byExt.FirstOrDefault(d => d.Operands.Any(o => o.MemOnly));
				if(regForm != null && memForm != null && regForm != memForm) {
					sb.AppendLine("\t\t\t\tif(i >= code.Length) return (null, 0);");
					sb.AppendLine("\t\t\t\tif((code[i] >> 6) == 3) {");
					EmitDefBody(sb, regForm, "\t\t\t\t\t");
					sb.AppendLine("\t\t\t\t} else {");
					EmitDefBody(sb, memForm, "\t\t\t\t\t");
					sb.AppendLine("\t\t\t\t}");
					sb.AppendLine("\t\t\t}");
					continue;
				}
			}
			if(byExt.Count > 1 || byExt[0].RegExtension >= 0) {
				// need ModRM.reg to disambiguate; all rows in a /N group carry ModRM
				sb.AppendLine("\t\t\t\tif(i >= code.Length) return (null, 0);");
				sb.AppendLine("\t\t\t\tvar regField = (code[i] >> 3) & 7;");
				sb.AppendLine("\t\t\t\tswitch(regField) {");
				foreach(var d in byExt.OrderBy(x => x.RegExtension)) {
					if(d.RegExtension < 0)
						throw new NotSupportedException($"(map,opcode) collision without /N: {d.Name}");
					sb.AppendLine($"\t\t\t\t\tcase {d.RegExtension}: {{");
					EmitDefBody(sb, d, "\t\t\t\t\t\t");
					sb.AppendLine("\t\t\t\t\t}");
				}
				sb.AppendLine("\t\t\t\t\tdefault: return (null, 0);");
				sb.AppendLine("\t\t\t\t}");
			} else
				EmitDefBody(sb, byExt[0], "\t\t\t\t");
			sb.AppendLine("\t\t\t}");
		}
		sb.AppendLine("\t\t\tdefault: return (null, 0);");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine("}");
		return sb.ToString();
	}

	static int BodyN;

	static void EmitDefBody(StringBuilder sb, XFusionDef def, string ind) {
		// Unique local names per body: a prefix-guarded child block's declaration would
		// conflict with the bare row's parent-scope declaration (CS0136).
		var m = $"m{++BodyN}";
		// Decode phase: ModRM if needed, then operand exprs in spec order.
		if(def.NeedsModRm) {
			sb.AppendLine($"{ind}if(i >= code.Length) return (null, 0);");
			sb.AppendLine($"{ind}i += Decode.ReadModRm(code[i..], mode, in p, out var {m});");
			var memOnly = def.Operands.Any(o => o.MemOnly);
			if(memOnly) sb.AppendLine($"{ind}if({m}.IsReg) return (null, 0);");
			if(def.Evex) {
				// disp8*N (SDM 2.7.5): N from the memory operand's shape.
				var memSpec = def.Operands.FirstOrDefault(o => o.Class is OpClass.XmmRm or OpClass.ModRmRm && !o.MemOnly || o.MemOnly);
				var n = memSpec?.Width switch {
					WCode.ss => "4",
					WCode.sd => "8",
					WCode.q => "8",
					WCode.d => "4",
					WCode.b => "1",
					_ => "16 << p.VecLen",  // full-vector tuple (dq/ps/pd/x)
				};
				sb.AppendLine($"{ind}Decode.ScaleDisp8(ref {m}, {n});");
			}
		}

		var opTexts = new List<string>();
		foreach(var spec in def.Operands)
			opTexts.Add(EmitOperand(sb, def, spec, ind, m));
		// EVEX: {k1}{z} decoration rides the destination (first operand).
		if(def.Evex && opTexts.Count > 0)
			opTexts[0] = $"{opTexts[0]} + Decode.EvexDecoration(in p)";

		// Format: template dasm string with $param -> operand text, positionally.
		// lock/rep prefixes render before the mnemonic (XED convention). A 0x66 on a
		// zero-operand insn has nothing to absorb it — XED renders it as 'data16 ' (66 90).
		// String ops (X/Y operands) DO render rep/repnz — the prefix is semantic there.
		var fmt = RenderDasm(def, opTexts);
		var data16 = def.Operands.Count == 0 ? "(p.OpSize ? \"data16 \" : \"\") + " : "";
		var isStringOp = def.Operands.Any(o => o.Class is OpClass.StrSrc or OpClass.StrDst);
		var repRender = isStringOp ? "(p.Rep ? \"rep \" : p.RepNz ? \"repnz \" : \"\") + " : "";
		sb.AppendLine($"{ind}return ({data16}{repRender}Decode.MnemonicPrefix(in p) + {fmt}, i);");
	}

	/// Emits decode statements for one operand; returns the C# expression producing its text.
	static string EmitOperand(StringBuilder sb, XFusionDef def, OperandSpec spec, string ind, string m) {
		var vw = def.D64 ? "p.VWidthD64(mode)" : "p.VWidth(mode)";
		string VWidthExpr() => vw;
		bool Packed() => spec.Width is WCode.ps or WCode.pd or WCode.dq or WCode.x;
		string VecPtrBits() => spec.Width switch {
			WCode.ss => "32", WCode.sd => "64", WCode.q => "64", WCode.d => "32",
			WCode.b => "8", WCode.w => "16",
			WCode.ps or WCode.pd or WCode.dq or WCode.x => "128",
			_ => throw new NotSupportedException($"vector width {spec.Width} for {spec.Text}")
		};
		string WidthExpr() => spec.Width switch {
			WCode.b => "8",
			WCode.w => "16",
			WCode.v => vw,
			WCode.z => "p.ZWidth(mode)",
			WCode.d => "32",
			WCode.q => "64",
			_ => throw new NotSupportedException($"width {spec.Width} for {spec.Text}")
		};

		switch(spec.Class) {
			case OpClass.ModRmRm when spec.MemOnly && spec.Width == WCode.none:
				// address-only operand (LEA): no size qualifier — XED renders bare 'ptr [...]'
				return $"Decode.MemOperandString(in {m}, in p, mode, 0, pc + (ulong)i)";
			case OpClass.ModRmRm when spec.MemOnly && spec.Width is WCode.ps or WCode.pd or WCode.dq or WCode.ss or WCode.sd or WCode.x: {
				var ptr = !Packed() ? VecPtrBits()
					: def.Evex ? $"p.VecLen == 2 ? 512 : p.VecLen == 1 ? 256 : {VecPtrBits()}"
					: $"p.VexL ? 256 : {VecPtrBits()}";
				return $"Decode.MemOperandString(in {m}, in p, mode, {ptr}, pc + (ulong)i)";
			}
			case OpClass.ModRmRm when spec.MemOnly:
				return $"Decode.MemOperandString(in {m}, in p, mode, {WidthExpr()}, pc + (ulong)i)";
			case OpClass.ModRmRm:
				return $"({m}.IsReg ? Decode.GprName({m}.Rm, {WidthExpr()}, p.Rex != 0) : Decode.MemOperandString(in {m}, in p, mode, {WidthExpr()}, pc + (ulong)i))";
			case OpClass.ModRmReg:
				return $"Decode.GprName({m}.Reg, {WidthExpr()}, p.Rex != 0)";
			case OpClass.ModRmSeg:
				return $"Decode.SegRegName({m}.Reg)";
			case OpClass.FixedReg when spec.SegName != null:
				return $"\"{spec.SegName.ToLowerInvariant()}\"";
			case OpClass.FixedReg when spec.FixedRegByte:
				return $"Decode.GprName({spec.FixedRegIndex}, 8, p.Rex != 0)";
			case OpClass.FixedReg when spec.FixedRegVSized:
				return $"Decode.GprName({spec.FixedRegIndex}, p.VWidth(mode), p.Rex != 0)";
			case OpClass.FixedReg:
				return $"Decode.GprName({spec.FixedRegIndex}, 16, false)";
			case OpClass.FixedInt:
				return $"\"0x{spec.FixedValue:x}\"";
			case OpClass.OpcodeReg: {
				var w = spec.Width == WCode.b ? "8" : VWidthExpr();
				return $"Decode.GprName((op & 7) | (p.RexB ? 8 : 0), {w}, p.Rex != 0)";
			}
			case OpClass.StrSrc:
				return $"Decode.StrOperand(6, {WidthExpr()}, in p, mode)";  // rSI
			case OpClass.StrDst:
				return $"Decode.StrOperand(7, {WidthExpr()}, in p, mode)";  // rDI
			case OpClass.XmmReg when def.Evex:
				return $"Decode.VecName({m}.Reg | (p.EvexRp ? 16 : 0), {(Packed() ? "p.VecLen" : "0")})";
			case OpClass.XmmReg: {
				var l = Packed() ? "p.VexL" : "false";  // scalar widths are L-ignored (LIG)
				return $"Decode.XmmName({m}.Reg, {l})";
			}
			case OpClass.XmmRm when def.Evex: {
				var ln = Packed() ? "p.VecLen" : "0";
				var ptr = Packed() ? $"p.VecLen == 2 ? 512 : p.VecLen == 1 ? 256 : {VecPtrBits()}" : VecPtrBits();
				// reg-form rm extends via X̄ (folded to Rex bit 1... X is bit 2): (RexX ? 16 : 0)
				return $"({m}.IsReg ? Decode.VecName({m}.Rm | (p.RexX ? 16 : 0), {ln}) : Decode.MemOperandString(in {m}, in p, mode, {ptr}, pc + (ulong)i))";
			}
			case OpClass.XmmRm: {
				var l = Packed() ? "p.VexL" : "false";
				var ptr = Packed() ? $"p.VexL ? 256 : {VecPtrBits()}" : VecPtrBits();
				return $"({m}.IsReg ? Decode.XmmName({m}.Rm, {l}) : Decode.MemOperandString(in {m}, in p, mode, {ptr}, pc + (ulong)i))";
			}
			case OpClass.XmmRmReg when def.Evex:
				return $"Decode.VecName({m}.Rm | (p.RexX ? 16 : 0), {(Packed() ? "p.VecLen" : "0")})";
			case OpClass.XmmRmReg: {
				var l = Packed() ? "p.VexL" : "false";
				return $"Decode.XmmName({m}.Rm, {l})";  // mod==11 enforced by MemOnly-inverse below
			}
			case OpClass.XmmVvvv when def.Evex:
				return $"Decode.VecName(p.VexVvvv, {(Packed() ? "p.VecLen" : "0")})";
			case OpClass.XmmVvvv: {
				var l = Packed() ? "p.VexL" : "false";
				return $"Decode.XmmName(p.VexVvvv, {l})";
			}
			case OpClass.GprVvvv:
				return $"Decode.GprName(p.VexVvvv, {VWidthExpr()}, true)";
			case OpClass.MaskReg:
				return $"Decode.MaskName({m}.Reg)";
			case OpClass.MaskRm:
				return $"Decode.MaskName({m}.Rm)";
			case OpClass.MmxReg:
				return $"Decode.MmxName({m}.Reg)";
			case OpClass.MmxRm:
				return $"({m}.IsReg ? Decode.MmxName({m}.Rm) : Decode.MemOperandString(in {m}, in p, mode, {VecPtrBits()}, pc + (ulong)i))";
			case OpClass.Imm: {
				var v = $"imm{BodyN}_{spec.Text.Replace("-", "_")}";
				// z-imms fetch 16/32 but the VALUE is sign-extended to the v-sized destination
				// (SDM: imm32 sign-extended in 64-bit ops). Render masked to destination width
				// (XED: 83 C0 FB = add eax, 0xfffffffb; 48 C7 C0 FF.. = mov rax, 0xffffffffffffffff).
				var sx = spec.SignExtended || spec.Width == WCode.z;
				var destW = spec.SignExtended || spec.Width == WCode.z ? VWidthExpr() : WidthExpr();
				sb.AppendLine($"{ind}var {v} = Decode.MaskToWidth(Decode.ReadImm(code, ref i, {WidthExpr()}, {(sx ? "true" : "false")}), {destW});");
				return $"$\"0x{{{v}:x}}\"";
			}
			case OpClass.RelBranch: {
				var v = $"rel{BodyN}_{spec.Text}";
				sb.AppendLine($"{ind}var {v} = Decode.ReadImm(code, ref i, {WidthExpr()}, true);");
				// target wraps at the mode's IP width (EIP in 32-bit mode)
				return $"$\"0x{{Decode.MaskToWidth((long)(pc + (ulong)i + (ulong){v}), mode == XMode.Bits64 ? 64 : mode == XMode.Bits32 ? 32 : 16):x}}\"";
			}
			case OpClass.MemOffset: {
				var v = $"moffs{BodyN}_{spec.Text}";
				sb.AppendLine($"{ind}var {v} = Decode.ReadImm(code, ref i, p.AWidth(mode), false);");
				return $"$\"[0x{{{v}:x}}]\"";
			}
			default:
				throw new NotSupportedException($"operand class {spec.Class} ({spec.Text})");
		}
	}

	/// dasm template: "add $lval, $rval" — parse the PTree (string-concat of PString +
	/// PName segments per ListParser.ParseString) into a C# interpolated string.
	static string RenderDasm(XFusionDef def, List<string> opTexts) {
		string Bind(string pname) {
			var idx = def.ParamNames.IndexOf(pname);
			if(idx < 0) throw new NotSupportedException($"dasm of {def.Mnemonic} references ${pname}, not a template param");
			return opTexts[idx];
		}

		// $(wname n16 n32 n64): mnemonic selected by effective operand width (98/99 class).
		// $(lname l0 l1): mnemonic selected by VEX.L (vzeroupper/vzeroall).
		string TryWname(PTree t) {
			if(t is PList wl && wl.Count == 4 && wl[0] is PName("wname")
				&& wl[1] is PName(var n16) && wl[2] is PName(var n32) && wl[3] is PName(var n64))
				return $"(p.VWidth(mode) switch {{ 16 => \"{n16}\", 32 => \"{n32}\", _ => \"{n64}\" }})";
			if(t is PList ll && ll.Count == 3 && ll[0] is PName("lname")
				&& ll[1] is PName(var l0) && ll[2] is PName(var l1))
				return $"(p.VexL ? \"{l1}\" : \"{l0}\")";
			return null;
		}

		switch(def.Dasm) {
			case PString { String: var s }:
				return $"\"{s}\"";
			case var t when TryWname(t) != null:
				return TryWname(t);
			case PName(var n):  // whole dasm is one $param (unusual but legal)
				return Bind(n);
			case PList l when l.Count > 0 && l[0] is PName("string-concat"): {
				var sb = new StringBuilder("$\"");
				foreach(var seg in l.Skip(1))
					switch(seg) {
						case PString { String: var s }: sb.Append(s.Replace("\"", "\\\"")); break;
						case PName(var n): sb.Append("{").Append(Bind(n)).Append("}"); break;
						case var w when TryWname(w) != null: sb.Append("{").Append(TryWname(w)).Append("}"); break;
						default: throw new NotSupportedException($"dasm segment {seg} in {def.Mnemonic}");
					}
				sb.Append('"');
				return sb.ToString();
			}
			default:
				throw new NotSupportedException($"dasm shape for {def.Mnemonic}: {def.Dasm}");
		}
	}
}
