using System.Text;
using CoreArchCompiler;

namespace XFusionGenerator;

/// Emits Generated/LiftTables.cs: per-template eval bodies as round-trippable
/// S-expr text (runtime re-parses via ListParser once, lazily) + per-DefId rows
/// (template index, operand spec texts) for bind construction. DESIGN
/// §Lift-wiring piece 2.
public static class LiftTablesGenerator {
	/// defs MUST be DisassemblerGenerator.BodyOrder (DefId order), not the raw list.
	public static string Generate(List<XFusionDef.Template> templates, List<XFusionDef> defs) {
		var sb = new StringBuilder();
		sb.AppendLine("// GENERATED by XFusionGenerator — do not edit.");
		sb.AppendLine("namespace XFusionCpu;");
		sb.AppendLine();
		sb.AppendLine("public static class LiftTables {");

		// templates: name, params, eval S-expr (the (block ...) form)
		var tIndex = new Dictionary<string, int>();
		sb.AppendLine("\t/// {mnemonic, space-joined params, eval S-expr}. Index = TemplateId.");
		sb.AppendLine("\tpublic static readonly (string Mnemonic, string Params, string Eval)[] Templates = [");
		foreach(var t in templates) {
			tIndex[t.Mnemonic] = tIndex.Count;
			sb.AppendLine($"\t\t({Q(t.Mnemonic)}, {Q(string.Join(' ', t.Params))}, {Q(Print(t.Eval))}),");
		}
		sb.AppendLine("\t];");
		sb.AppendLine();

		// defs: DefId (1-based, [0] unused) -> template index + operand specs + op width class
		sb.AppendLine("\t/// DefId -> (TemplateId, space-joined operand specs, D64). [0] unused.");
		sb.AppendLine("\tpublic static readonly (int TemplateId, string Specs, bool D64)[] Defs = [");
		sb.AppendLine("\t\t(-1, null, false),");
		foreach(var d in defs)
			sb.AppendLine($"\t\t({tIndex[d.Mnemonic]}, {Q(string.Join(' ', d.Operands.Select(o => o.Text)))}, {(d.D64 ? "true" : "false")}),");
		sb.AppendLine("\t];");
		sb.AppendLine("}");
		return sb.ToString();
	}

	static string Q(string s) => s == null ? "null" : "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

	/// Round-trippable S-expr print (ListParser-compatible: names, ints, strings, lists).
	public static string Print(PTree t) => t switch {
		PName(var n) => n,
		PInt(var v) => "0x" + v.ToString("x"),
		PString { String: var s } => "\"" + s.Replace("\"", "\\\"") + "\"",
		PList l => "(" + string.Join(' ', l.Select(Print)) + ")",
		_ => throw new NotSupportedException($"print {t.GetType().Name}")
	};
}
