using System.Text;

namespace XFusionGenerator;

/// Rust-target sibling of `DisassemblerGenerator` — emits `disassembler.rs`
/// (the (map, opcode) dispatch that fills `DecodedInsn`). Same grouping/discrimination
/// logic; Rust syntax; DECODE-HALF ONLY (no disasm-string render — the recompiler
/// doesn't need it; a Rust render can be added later for a debug-disasm).
///
/// Output calls the hand-ported `decode.rs` primitives (scan_prefixes/read_modrm/
/// read_imm) exactly as the C# generated code calls Decode.cs.
public static class RustDisasmGen {
    static int BodyN;

    public static string Generate(List<XFusionDef> defs) {
        BodyN = 0;
        var sb = new StringBuilder();
        sb.AppendLine("// GENERATED by XFusionGenerator/RustDisasmGen — do not edit.");
        sb.AppendLine("#![allow(unused_variables, unused_parens, non_snake_case, unreachable_code, unused_mut)]");
        sb.AppendLine("use crate::decode::{XMode, OpcodeMap, DecodedInsn,");
        sb.AppendLine("                    scan_prefixes, read_modrm, read_imm};");
        sb.AppendLine();
        sb.AppendLine("pub fn decode_insn(code: &[u8], mode: XMode) -> Option<DecodedInsn> {");
        sb.AppendLine("    // x86 caps instruction length at 15 bytes (#UD past that).");
        sb.AppendLine("    let code = if code.len() > 15 { &code[..15] } else { code };");
        sb.AppendLine("    let (p_len, mut p) = scan_prefixes(code, mode);");
        sb.AppendLine("    let mut i = p_len;");
        sb.AppendLine("    if i >= code.len() { return None; }");
        sb.AppendLine("    let mut op = code[i]; i += 1;");
        sb.AppendLine("    let map = if p.vex_valid {");
        sb.AppendLine("        match p.vex_map { 1 => OpcodeMap::TwoByte0F, 2 => OpcodeMap::ThreeByte0F38, 3 => OpcodeMap::ThreeByte0F3A, _ => return None }");
        sb.AppendLine("    } else if op == 0x0F {");
        sb.AppendLine("        if i >= code.len() { return None; }");
        sb.AppendLine("        op = code[i]; i += 1;");
        sb.AppendLine("        if op == 0x38 { if i >= code.len() { return None; } op = code[i]; i += 1; OpcodeMap::ThreeByte0F38 }");
        sb.AppendLine("        else if op == 0x3A { if i >= code.len() { return None; } op = code[i]; i += 1; OpcodeMap::ThreeByte0F3A }");
        sb.AppendLine("        else { OpcodeMap::TwoByte0F }");
        sb.AppendLine("    } else { OpcodeMap::OneByte };");
        sb.AppendLine("    let mut d = DecodedInsn::default();");
        sb.AppendLine();

        // Same grouping as DisassemblerGenerator (kept in lockstep — the C# side is
        // XED-verified; this side must produce the SAME def_id for the same bytes).
        // A plus_r def's r=0 slot may collide with an exact def at the same opcode
        // (only case: 0x90 NOP vs XCHG rAX,r0). PREVIOUSLY the exact-set filter dropped
        // the plus_r row entirely there — wrong when REX.B is set: 41 90 = XCHG r8d,eax,
        // NOT nop. Now: keep BOTH in the group; the byExt arm-emit below discriminates
        // by p.rex_b() (rex_b → the plus_r def targeting r8+, else → the exact def).
        // Found by the sweep's round-trip gate on its first fire.
        var dispatchRows = defs.SelectMany(d => d.PlusR
            ? Enumerable.Range(0, 8).Select(r => (Op: (byte)(d.Opcode + r), Def: d))
            : new[] { (Op: d.Opcode, Def: d) });
        var groups = dispatchRows.GroupBy(x => (x.Def.Map, x.Op))
            .OrderBy(g => g.Key.Map).ThenBy(g => g.Key.Op);

        sb.AppendLine("    match (map, op) {");
        foreach(var g in groups) {
            var mapName = g.Key.Map.ToString();
            sb.AppendLine($"        (OpcodeMap::{mapName}, 0x{g.Key.Op:X2}) => {{");

            // VEX rows first (under p.vex_valid).
            var vexRows = g.Select(x => x.Def).Where(d => d.Vex != VexMode.None).ToList();
            if(vexRows.Count > 0) {
                sb.AppendLine("            if p.vex_valid {");
                foreach(var vd in vexRows) {
                    var conds = new List<string> {
                        vd.Evex ? "p.evex_valid" : "!p.evex_valid",
                        vd.MandatoryPrefix switch {
                            "rep" => "p.rep", "repnz" => "p.rep_nz", "opsize" => "p.op_size",
                            null => "!p.op_size && !p.rep && !p.rep_nz",
                            _ => throw new NotSupportedException(vd.MandatoryPrefix)
                        }
                    };
                    if(vd.VexW is not null) conds.Add(vd.VexW.Value ? "p.rex_w()" : "!p.rex_w()");
                    if(vd.Vex == VexMode.TwoSrc) conds.Add("p.vex_vvvv == 0");
                    sb.AppendLine($"                if {string.Join(" && ", conds)} {{");
                    EmitDefBody(sb, vd, "                    ");
                    sb.AppendLine("                }");
                }
                sb.AppendLine("                return None;");
                sb.AppendLine("            }");
            } else {
                sb.AppendLine("            if p.vex_valid { return None; }");
            }

            // Mandatory-prefix legacy rows.
            foreach(var pg in g.Select(x => x.Def)
                     .Where(d => d.MandatoryPrefix != null && d.Vex == VexMode.None)
                     .GroupBy(d => d.MandatoryPrefix)) {
                var (cond, clear) = pg.Key switch {
                    "rep" => ("p.rep", "p.rep = false;"),
                    "repnz" => ("p.rep_nz", "p.rep_nz = false;"),
                    "opsize" => ("p.op_size", "p.op_size = false;"),
                    _ => throw new NotSupportedException(pg.Key)
                };
                sb.AppendLine($"            if {cond} {{");
                sb.AppendLine($"                {clear}");
                var pdefs = pg.ToList();
                if(pdefs.Count > 1 || pdefs[0].RegExtension >= 0) {
                    sb.AppendLine("                if i >= code.len() { return None; }");
                    sb.AppendLine("                match (code[i] >> 3) & 7 {");
                    foreach(var pd in pdefs.OrderBy(x => x.RegExtension)) {
                        if(pd.RegExtension < 0)
                            throw new NotSupportedException($"prefix-group collision without /N: {pd.Name}");
                        sb.AppendLine($"                    {pd.RegExtension} => {{");
                        EmitDefBody(sb, pd, "                        ");
                        sb.AppendLine("                    }");
                    }
                    sb.AppendLine("                    _ => return None,");
                    sb.AppendLine("                }");
                } else {
                    EmitDefBody(sb, pdefs[0], "                ");
                }
                sb.AppendLine("            }");
            }

            var byExt = g.Select(x => x.Def)
                .Where(d => d.MandatoryPrefix == null && d.Vex == VexMode.None)
                .Distinct().ToList();

            // (exact + plus_r) collision at this opcode: the plus_r def only reaches
            // this slot's opcode via its r=0 encoding, and REX.B extends that to r8.
            // Without REX.B the exact def wins (90=NOP); with REX.B it's the plus_r
            // def targeting r8 (41 90 = XCHG r8d,eax). Only 0x90 in practice.
            if(byExt.Count == 2 && byExt.Count(d => d.PlusR) == 1) {
                var plusR = byExt.First(d => d.PlusR);
                var exact = byExt.First(d => !d.PlusR);
                sb.AppendLine("            if p.rex_b() {");
                EmitDefBody(sb, plusR, "                ");
                sb.AppendLine("            }");
                EmitDefBody(sb, exact, "            ");
                sb.AppendLine("        }");
                continue;
            }
            if(byExt.Count == 0) {
                sb.AppendLine("            return None;");
                sb.AppendLine("        }");
                continue;
            }

            // Vector-group prefix-reject (bare row must reject unclaimed 66/F3/F2).
            var isVectorGroup = g.Select(x => x.Def).Any(d => d.Operands.Any(o =>
                o.Class is OpClass.XmmReg or OpClass.XmmRm or OpClass.XmmRmReg
                    or OpClass.MmxReg or OpClass.MmxRm));
            if(isVectorGroup) {
                var claimed = g.Select(x => x.Def.MandatoryPrefix).Where(x => x != null).ToHashSet();
                var rejects = new List<string>();
                if(!claimed.Contains("opsize")) rejects.Add("p.op_size");
                if(!claimed.Contains("rep")) rejects.Add("p.rep");
                if(!claimed.Contains("repnz")) rejects.Add("p.rep_nz");
                if(rejects.Count > 0)
                    sb.AppendLine($"            if {string.Join(" || ", rejects)} {{ return None; }}");
            }

            // mod-field discrimination (regonly + memonly pair, no /N — 0F 12 movhlps/movlps).
            if(byExt.Count == 2 && byExt.All(d => d.RegExtension < 0)) {
                var regForm = byExt.FirstOrDefault(d => d.Operands.Any(o => o.Class == OpClass.XmmRmReg));
                var memForm = byExt.FirstOrDefault(d => d.Operands.Any(o => o.MemOnly));
                if(regForm != null && memForm != null && regForm != memForm) {
                    sb.AppendLine("            if i >= code.len() { return None; }");
                    sb.AppendLine("            if (code[i] >> 6) == 3 {");
                    EmitDefBody(sb, regForm, "                ");
                    sb.AppendLine("            } else {");
                    EmitDefBody(sb, memForm, "                ");
                    sb.AppendLine("            }");
                    sb.AppendLine("        }");
                    continue;
                }
            }

            if(byExt.Count > 1 || byExt[0].RegExtension >= 0) {
                sb.AppendLine("            if i >= code.len() { return None; }");
                sb.AppendLine("            let (reg_field, mod_is_11, rm_field) = ((code[i] >> 3) & 7, (code[i] >> 6) == 3, code[i] & 7);");
                sb.AppendLine("            match reg_field {");
                foreach(var eg in byExt.GroupBy(x => x.RegExtension).OrderBy(x => x.Key)) {
                    if(eg.Key < 0)
                        throw new NotSupportedException($"(map,opcode) collision without /N: {eg.First().Name}");
                    sb.AppendLine($"                {eg.Key} => {{");
                    var members = eg.ToList();
                    if(members.Count == 1 && members[0].Mod11 == null && members[0].RmExact < 0) {
                        EmitDefBody(sb, members[0], "                    ");
                    } else {
                        foreach(var dd in members.OrderBy(x => x.RmExact < 0 ? 1 : 0)) {
                            var conds = new List<string>();
                            if(dd.Mod11 == true) conds.Add("mod_is_11");
                            if(dd.Mod11 == false) conds.Add("!mod_is_11");
                            if(dd.RmExact >= 0) conds.Add($"rm_field == {dd.RmExact}");
                            sb.AppendLine($"                    if {(conds.Count > 0 ? string.Join(" && ", conds) : "true")} {{");
                            EmitDefBody(sb, dd, "                        ");
                            sb.AppendLine("                    }");
                        }
                        sb.AppendLine("                    return None;");
                    }
                    sb.AppendLine("                }");
                }
                sb.AppendLine("                _ => return None,");
                sb.AppendLine("            }");
            } else {
                EmitDefBody(sb, byExt[0], "            ");
            }
            sb.AppendLine("        }");
        }
        sb.AppendLine("        _ => return None,");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Def-id → mnemonic table (for debugging / the eventual lift-table join).
        // BodyN order = the C# DisassemblerGenerator's BodyOrder — MUST match so
        // def_ids are cross-referenceable between the C# and Rust decoders.
        sb.AppendLine("pub const DEF_MNEMONICS: &[&str] = &[");
        sb.AppendLine("    \"\",  // [0] unused");
        foreach(var d in BodyOrder)
            sb.AppendLine($"    \"{d.Mnemonic}\",");
        sb.AppendLine("];");

        return sb.ToString();
    }

    /// Def-id assignment order (populated during Generate; matches C# side's BodyOrder).
    public static readonly List<XFusionDef> BodyOrder = new();

    // SDM closed set (transcribed from DisassemblerGenerator.Lockable — kept in lockstep).
    static readonly HashSet<string> Lockable = [
        "ADD", "ADC", "AND", "BTC", "BTR", "BTS", "CMPXCHG", "DEC", "INC",
        "NEG", "NOT", "OR", "SBB", "SUB", "XOR", "XADD", "XCHG",
    ];

    static void EmitDefBody(StringBuilder sb, XFusionDef def, string ind) {
        BodyN++;
        BodyOrder.Add(def);
        // LOCK legality (SDM closed set, memory destination only).
        if(!Lockable.Contains(def.Mnemonic) || def.Operands.Count == 0
                || def.Operands[0].Class != OpClass.ModRmRm)
            sb.AppendLine($"{ind}if p.lock {{ return None; }}");

        if(def.NeedsModRm) {
            sb.AppendLine($"{ind}let (m_len, m) = read_modrm(&code[i..], mode, &p)?;");
            sb.AppendLine($"{ind}i += m_len;");
            if(def.Operands.Any(o => o.MemOnly))
                sb.AppendLine($"{ind}if m.is_reg {{ return None; }}");
            if(Lockable.Contains(def.Mnemonic) && def.Operands.Count > 0
                    && def.Operands[0].Class == OpClass.ModRmRm)
                sb.AppendLine($"{ind}if p.lock && m.is_reg {{ return None; }}");
            if(def.Evex) {
                // ‡ disp8*N scaling (SDM 2.7.5) — decode.rs needs a scale_disp8; deferred
                // to EVEX-coverage phase. For now the disp is unscaled (a decode-length
                // difference vs XED on EVEX-with-disp8 — flagged in the corpus-diff).
                sb.AppendLine($"{ind}// TODO: disp8*N scaling (EVEX)");
            }
            sb.AppendLine($"{ind}d.m = m;");
        }

        // Imm-consuming operands (Imm/RelBranch/MemOffset/FarPtr) — read + assign to
        // imm0/imm1 in spec-order. Everything else consumes no bytes post-ModRM.
        var immSlot = 0;
        foreach(var spec in def.Operands) {
            var immField = immSlot == 0 ? "d.imm0" : "d.imm1";
            switch(spec.Class) {
                case OpClass.Imm: {
                    var (bits, sext) = ImmBitsExpr(spec, def);
                    sb.AppendLine($"{ind}{immField} = read_imm(code, &mut i, {bits}, {sext});");
                    immSlot++;
                    break;
                }
                case OpClass.RelBranch: {
                    var bits = spec.Width switch {
                        WCode.b => "8",
                        WCode.z => def.D64 ? "p.branch_z_width(mode)" : "p.z_width(mode)",
                        WCode.d => "32",
                        _ => throw new NotSupportedException($"Jz width {spec.Width}")
                    };
                    // Rel-branches are always sign-extended.
                    sb.AppendLine($"{ind}{immField} = read_imm(code, &mut i, {bits}, true);");
                    immSlot++;
                    break;
                }
                case OpClass.MemOffset: {
                    // moffs — address-sized immediate, unsigned.
                    sb.AppendLine($"{ind}{immField} = read_imm(code, &mut i, p.a_width(mode), false);");
                    immSlot++;
                    break;
                }
                case OpClass.FarPtr: {
                    // ptr16:16 / ptr16:32 — offset (v-width) then selector (16-bit).
                    // Pack into imm0=offset, imm1=selector.
                    var offBits = "p.z_width(mode)";
                    sb.AppendLine($"{ind}d.imm0 = read_imm(code, &mut i, {offBits}, false);");
                    sb.AppendLine($"{ind}d.imm1 = read_imm(code, &mut i, 16, false);");
                    immSlot = 2;
                    break;
                }
                case OpClass.ModRmSeg: {
                    // reg 6/7 = #UD; CS-as-dest = #UD.
                    var csBad = def.Operands.Count > 0 && ReferenceEquals(def.Operands[0], spec)
                        ? " || m.reg == 1" : "";
                    sb.AppendLine($"{ind}if m.reg > 5{csBad} {{ return None; }}");
                    break;
                }
                // All others: no bytes consumed, no d.* to fill (values derive from p/m/op).
            }
        }

        sb.AppendLine($"{ind}d.def_id = {BodyN};");
        sb.AppendLine($"{ind}d.len = i as u32;");
        sb.AppendLine($"{ind}d.op = op;");
        sb.AppendLine($"{ind}d.p = p;");
        sb.AppendLine($"{ind}return Some(d);");
    }

    /// (bits-expr, sign-extend?) for an OpClass.Imm operand. Iz is 32-bit sign-extended
    /// to 64 at REX.W (but read as 32 bits); Iv reads full v-width; Ib sign-extends when
    /// used with a wider destination (the 83 /N Ev,Ib class).
    static (string bits, string sext) ImmBitsExpr(OperandSpec spec, XFusionDef def) => spec.Width switch {
        WCode.b => ("8", "true"),   // Ib always sign-extends (83 /N; the SDM's imm8→imm32 sext)
        WCode.w => ("16", "false"),
        WCode.v => (def.D64 ? "p.v_width_d64(mode)" : "p.v_width(mode)", "false"),
        WCode.z => ("p.z_width(mode)", "true"),  // Iz: 32-bit sext to 64 at REX.W
        WCode.d => ("32", "false"),
        _ => throw new NotSupportedException($"Imm width {spec.Width} for {spec.Text}")
    };
}
