using System.Text;

namespace XFusionGenerator;

/// Emits `sweep_defs.rs`: a per-XFusionDef table of encoding facts (map/opcode/
/// prefix/reg-ext/plus-r/d64/mod11 + per-operand class+width). The Rust-side
/// generic encoder (sweep.rs) consumes this to synthesize every valid encoding
/// per def × register-combo × opsize × imm-boundary, then TrackingState + the
/// pre-state grid produce corpus rows for the silicon runner.
///
/// Design: C# exports FACTS (this file), Rust does the ENCODING (one generic
/// encoder, not per-def generated code). Round-trip verify = decode_insn on
/// every synthesized encoding must succeed with matching mnemonic — the
/// XED-verified decoder is the encoder's oracle.
public static class SweepGen {
	static string OpClsRust(OpClass c) => c switch {
		OpClass.ModRmRm    => "Erm",
		OpClass.ModRmReg   => "Greg",
		OpClass.ModRmSeg   => "Sreg",
		OpClass.Imm        => "Imm",
		OpClass.RelBranch  => "Rel",
		OpClass.FixedReg   => "FixR",
		OpClass.FixedInt   => "FixI",
		OpClass.OpcodeReg  => "Zopc",
		OpClass.StrSrc     => "StrS",
		OpClass.StrDst     => "StrD",
		OpClass.XmmReg     => "Vxmm",
		OpClass.XmmRm      => "Wxmm",
		OpClass.XmmRmReg   => "Uxmm",
		OpClass.XmmVvvv    => "Hxmm",
		OpClass.GprVvvv    => "Hgpr",
		OpClass.FpuTop     => "FpuT",
		OpClass.FpuSti     => "FpuI",
		OpClass.MaskReg    => "Kreg",
		OpClass.MaskRm     => "Krm",
		OpClass.MmxReg     => "Preg",
		OpClass.MmxRm      => "Qrm",
		OpClass.MemOffset  => "Moff",
		OpClass.FarPtr     => "FarP",
		_ => throw new NotSupportedException($"OpClass {c}")
	};

	static string WCodeRust(WCode w) => w switch {
		WCode.b => "B", WCode.w => "W", WCode.v => "V", WCode.z => "Z",
		WCode.d => "D", WCode.q => "Q", WCode.p => "P",
		WCode.ps => "Ps", WCode.pd => "Pd", WCode.ss => "Ss", WCode.sd => "Sd",
		WCode.dq => "Dq", WCode.x => "X", WCode.none => "N",
		_ => throw new NotSupportedException($"WCode {w}")
	};

	public static string Generate(List<XFusionDef> defs) {
		var sb = new StringBuilder();
		sb.AppendLine("// GENERATED by XFusionGenerator/SweepGen — do not edit.");
		sb.AppendLine("// Per-def encoding facts for the exhaustive silicon sweep. The Rust");
		sb.AppendLine("// encoder in sweep.rs consumes these to synthesize every valid encoding.");
		sb.AppendLine("#![allow(dead_code)]");
		sb.AppendLine();
		sb.AppendLine("#[derive(Copy, Clone, Debug, PartialEq, Eq)]");
		sb.AppendLine("pub enum SwCls { Erm, Greg, Sreg, Imm, Rel, FixR, FixI, Zopc, StrS, StrD,");
		sb.AppendLine("                 Vxmm, Wxmm, Uxmm, Hxmm, Hgpr, FpuT, FpuI, Kreg, Krm, Preg, Qrm, Moff, FarP }");
		sb.AppendLine("#[derive(Copy, Clone, Debug, PartialEq, Eq)]");
		sb.AppendLine("pub enum SwW { B, W, V, Z, D, Q, P, Ps, Pd, Ss, Sd, Dq, X, N }");
		sb.AppendLine();
		sb.AppendLine("#[derive(Copy, Clone, Debug)]");
		sb.AppendLine("pub struct SwOp {");
		sb.AppendLine("    pub cls: SwCls,");
		sb.AppendLine("    pub w: SwW,");
		sb.AppendLine("    pub mem_only: bool,");
		sb.AppendLine("    pub sign_ext: bool,");
		sb.AppendLine("    pub fix_idx: i8,     // FixedReg: GPR index; else -1");
		sb.AppendLine("    pub fix_val: i32,    // FixedInt: literal value; else 0");
		sb.AppendLine("}");
		sb.AppendLine("#[derive(Copy, Clone, Debug)]");
		sb.AppendLine("pub struct SwDef {");
		sb.AppendLine("    pub mnem: &'static str,");
		sb.AppendLine("    pub map: u8,          // 0=1B, 1=0F, 2=0F38, 3=0F3A");
		sb.AppendLine("    pub opcode: u8,");
		sb.AppendLine("    pub reg_ext: i8,      // /0../7 or -1");
		sb.AppendLine("    pub mprefix: u8,      // 0 | 0x66 | 0xF2 | 0xF3");
		sb.AppendLine("    pub plus_r: bool,");
		sb.AppendLine("    pub d64: bool,");
		sb.AppendLine("    pub mod11: i8,        // -1=either, 0=mem-only, 1=reg-only");
		sb.AppendLine("    pub vex: u8,          // 0=legacy, 1=vex-2src, 2=vex-3src, 3=evex");
		sb.AppendLine("    pub ops: &'static [SwOp],");
		sb.AppendLine("}");
		sb.AppendLine();

		byte MPrefix(string p) => p switch {
			"opsize" => 0x66, "rep" => 0xF3, "repnz" => 0xF2, null => 0,
			_ => throw new NotSupportedException($"mand-prefix {p}")
		};
		byte MapByte(OpcodeMap m) => m switch {
			OpcodeMap.OneByte => 0, OpcodeMap.TwoByte0F => 1,
			OpcodeMap.ThreeByte0F38 => 2, OpcodeMap.ThreeByte0F3A => 3,
			_ => throw new NotSupportedException()
		};
		byte VexByte(XFusionDef d) => d.Evex ? (byte)3 : d.Vex switch {
			VexMode.None => (byte)0, VexMode.TwoSrc => (byte)1, VexMode.ThreeSrc => (byte)2,
			_ => throw new NotSupportedException()
		};

		// One SwDef per XFusionDef. Order = defs list order (= .isa file order after
		// feature-gate filtering). NOT the same as decoder's def_id (which is per
		// dispatch-row); the sweep round-trips via decode_insn + mnemonic-match, so
		// def_id correlation isn't load-bearing.
		sb.AppendLine("pub static SWEEP_DEFS: &[SwDef] = &[");
		foreach(var d in defs) {
			var mod11 = d.Mod11 switch { true => 1, false => 0, null => -1 };
			sb.Append($"    SwDef {{ mnem: \"{d.Mnemonic}\", map: {MapByte(d.Map)}, opcode: 0x{d.Opcode:X2}, ");
			sb.Append($"reg_ext: {d.RegExtension}, mprefix: 0x{MPrefix(d.MandatoryPrefix):X2}, ");
			sb.Append($"plus_r: {(d.PlusR ? "true" : "false")}, d64: {(d.D64 ? "true" : "false")}, ");
			sb.Append($"mod11: {mod11}, vex: {VexByte(d)}, ops: &[");
			foreach(var o in d.Operands) {
				var fixIdx = o.Class == OpClass.FixedReg && o.SegName == null ? o.FixedRegIndex : -1;
				var fixVal = o.Class == OpClass.FixedInt ? o.FixedValue : 0;
				sb.Append($"SwOp{{cls:SwCls::{OpClsRust(o.Class)},w:SwW::{WCodeRust(o.Width)},");
				sb.Append($"mem_only:{(o.MemOnly ? "true" : "false")},sign_ext:{(o.SignExtended ? "true" : "false")},");
				sb.Append($"fix_idx:{fixIdx},fix_val:{fixVal}}},");
			}
			sb.AppendLine("] },");
		}
		sb.AppendLine("];");
		sb.AppendLine();
		sb.AppendLine($"// {defs.Count} defs. Legacy (vex==0) count = {defs.Count(d => d.Vex == VexMode.None && !d.Evex)}.");
		return sb.ToString();
	}
}
