#include "nv.h"

#include <iostream>

void nv::InitializeGraphics(void*, uint64_t) {
    std::cout << "nv::InitializeGraphics called!" << std::endl;
}

// nv::SetGraphicsAllocator(
//  void* (*)(unsigned long, unsigned long, void*),
//  void (*)(void*, void*),
//  void* (*)(void*, unsigned long, void*),
//  void*)
void nv::SetGraphicsAllocator(void*, void*, void*, void*) {
    std::cout << "nv::SetGraphicsAllocator called!" << std::endl;
}

void nvnDeviceBuilderSetDefaults(void* deviceBuilder) {
    std::cout << "nvnDeviceBuilderSetDefaults called!" << std::endl;
}
void nvnDeviceBuilderSetFlags(void* deviceBuilder, uint32_t flags) {
    std::cout << "nvnDeviceBuilderSetFlags (" << flags << ") called!" << std::endl;
}

// according to symbols this seems to be NVNDevice...? or one of them are
void nvnDeviceInitialize(void* unk, void* device) {
    std::cout << "nvnDeviceInitialize called!" << std::endl;
}

// guesses
void nvnDeviceGetInteger(void* device, int field, int32_t* value) {
    std::cout << "nvnDeviceGetInteger(" << field << ") called!" << std::endl;
}

void nvnDeviceSetWindowOriginMode(void* device, const int mode) {
    std::cout << "nvnDeviceSetWindowOriginMode (" << mode << ") called!" << std::endl;
}

void nvnMemoryPoolBuilderSetDevice(void* memoryPoolBuilder, void* device) {
    std::cout << "nvnMemoryPoolBuilderSetDevice called!" << std::endl;
}

void nvnMemoryPoolBuilderSetDefaults(void* memoryPoolBuilder) {
    std::cout << "nvnMemoryPoolBuilderSetDefaults called!" << std::endl;
}

void nvnMemoryPoolBuilderSetFlags(void* memoryPoolBuilder, const uint32_t flags) {
    std::cout << "nvnMemoryPoolBuilderSetFlags (" << flags << ") called!" << std::endl;
}

void nvnMemoryPoolBuilderSetStorage(void* memoryPoolBuilder, void* storage, uint32_t size /* ? */) {
    std::cout << "nvnMemoryPoolBuilderSetStorage called! size?: " << size << std::endl;
}

void nvnMemoryPoolInitialize(void** memoryPool, void* memoryPoolBuilder) {
    std::cout << "nvnMemoryPoolInitialize called!" << std::endl;
}

#define NVN_STUB(name) void name() { std::cout << #name " stub!" << std::endl; __builtin_trap(); exit(-1); }

NVN_STUB(nvnBlendStateGetAdvancedMode)
NVN_STUB(nvnBlendStateGetAdvancedNormalizedDst)
NVN_STUB(nvnBlendStateGetAdvancedOverlap)
NVN_STUB(nvnBlendStateGetAdvancedPremultipliedSrc)
NVN_STUB(nvnBlendStateGetBlendEquation)
NVN_STUB(nvnBlendStateGetBlendFunc)
NVN_STUB(nvnBlendStateGetBlendTarget)
NVN_STUB(nvnBlendStateSetAdvancedMode)
NVN_STUB(nvnBlendStateSetAdvancedNormalizedDst)
NVN_STUB(nvnBlendStateSetAdvancedOverlap)
NVN_STUB(nvnBlendStateSetAdvancedPremultipliedSrc)
NVN_STUB(nvnBlendStateSetBlendEquation)
NVN_STUB(nvnBlendStateSetBlendFunc)
NVN_STUB(nvnBlendStateSetBlendTarget)
NVN_STUB(nvnBlendStateSetDefaults)
NVN_STUB(nvnBufferBuilderGetMemoryOffset)
NVN_STUB(nvnBufferBuilderGetMemoryPool)
NVN_STUB(nvnBufferBuilderGetSize)
NVN_STUB(nvnBufferBuilderSetDefaults)
NVN_STUB(nvnBufferBuilderSetDevice)
NVN_STUB(nvnBufferBuilderSetStorage)
NVN_STUB(nvnBufferFinalize)
NVN_STUB(nvnBufferFlushMappedRange)
NVN_STUB(nvnBufferGetAddress)
NVN_STUB(nvnBufferGetDebugID)
NVN_STUB(nvnBufferGetMemoryOffset)
NVN_STUB(nvnBufferGetMemoryPool)
NVN_STUB(nvnBufferGetSize)
NVN_STUB(nvnBufferInitialize)
NVN_STUB(nvnBufferInvalidateMappedRange)
NVN_STUB(nvnBufferMap)
NVN_STUB(nvnBufferSetDebugLabel)
NVN_STUB(nvnChannelMaskStateGetChannelMask)
NVN_STUB(nvnChannelMaskStateSetChannelMask)
NVN_STUB(nvnChannelMaskStateSetDefaults)
NVN_STUB(nvnColorStateGetAlphaTest)
NVN_STUB(nvnColorStateGetBlendEnable)
NVN_STUB(nvnColorStateGetLogicOp)
NVN_STUB(nvnColorStateSetAlphaTest)
NVN_STUB(nvnColorStateSetBlendEnable)
NVN_STUB(nvnColorStateSetDefaults)
NVN_STUB(nvnColorStateSetLogicOp)
NVN_STUB(nvnCommandBufferAddCommandMemory)
NVN_STUB(nvnCommandBufferAddControlMemory)
NVN_STUB(nvnCommandBufferBarrier)
NVN_STUB(nvnCommandBufferBeginRecording)
NVN_STUB(nvnCommandBufferBeginTransformFeedback)
NVN_STUB(nvnCommandBufferBindBlendState)
NVN_STUB(nvnCommandBufferBindChannelMaskState)
NVN_STUB(nvnCommandBufferBindColorState)
NVN_STUB(nvnCommandBufferBindCoverageModulationTable)
NVN_STUB(nvnCommandBufferBindDepthStencilState)
NVN_STUB(nvnCommandBufferBindImage)
NVN_STUB(nvnCommandBufferBindImages)
NVN_STUB(nvnCommandBufferBindMultisampleState)
NVN_STUB(nvnCommandBufferBindPolygonState)
NVN_STUB(nvnCommandBufferBindProgram)
NVN_STUB(nvnCommandBufferBindStorageBuffer)
NVN_STUB(nvnCommandBufferBindStorageBuffers)
NVN_STUB(nvnCommandBufferBindTexture)
NVN_STUB(nvnCommandBufferBindTextures)
NVN_STUB(nvnCommandBufferBindTransformFeedbackBuffer)
NVN_STUB(nvnCommandBufferBindTransformFeedbackBuffers)
NVN_STUB(nvnCommandBufferBindUniformBuffer)
NVN_STUB(nvnCommandBufferBindUniformBuffers)
NVN_STUB(nvnCommandBufferBindVertexAttribState)
NVN_STUB(nvnCommandBufferBindVertexBuffer)
NVN_STUB(nvnCommandBufferBindVertexBuffers)
NVN_STUB(nvnCommandBufferBindVertexStreamState)
NVN_STUB(nvnCommandBufferCallCommands)
NVN_STUB(nvnCommandBufferClearBuffer)
NVN_STUB(nvnCommandBufferClearColor)
NVN_STUB(nvnCommandBufferClearColori)
NVN_STUB(nvnCommandBufferClearColorui)
NVN_STUB(nvnCommandBufferClearDepthStencil)
NVN_STUB(nvnCommandBufferClearTexture)
NVN_STUB(nvnCommandBufferClearTexturei)
NVN_STUB(nvnCommandBufferClearTextureui)
NVN_STUB(nvnCommandBufferCopyBufferToBuffer)
NVN_STUB(nvnCommandBufferCopyBufferToTexture)
NVN_STUB(nvnCommandBufferCopyCommands)
NVN_STUB(nvnCommandBufferCopyTextureToBuffer)
NVN_STUB(nvnCommandBufferCopyTextureToTexture)
NVN_STUB(nvnCommandBufferDiscardColor)
NVN_STUB(nvnCommandBufferDiscardDepthStencil)
NVN_STUB(nvnCommandBufferDispatchCompute)
NVN_STUB(nvnCommandBufferDispatchComputeIndirect)
NVN_STUB(nvnCommandBufferDownsample)
NVN_STUB(nvnCommandBufferDrawArrays)
NVN_STUB(nvnCommandBufferDrawArraysIndirect)
NVN_STUB(nvnCommandBufferDrawArraysInstanced)
NVN_STUB(nvnCommandBufferDrawElements)
NVN_STUB(nvnCommandBufferDrawElementsBaseVertex)
NVN_STUB(nvnCommandBufferDrawElementsIndirect)
NVN_STUB(nvnCommandBufferDrawElementsInstanced)
NVN_STUB(nvnCommandBufferDrawTexture)
NVN_STUB(nvnCommandBufferDrawTransformFeedback)
NVN_STUB(nvnCommandBufferEndRecording)
NVN_STUB(nvnCommandBufferEndTransformFeedback)
NVN_STUB(nvnCommandBufferFenceSync)
NVN_STUB(nvnCommandBufferFinalize)
NVN_STUB(nvnCommandBufferGetCommandMemoryFree)
NVN_STUB(nvnCommandBufferGetCommandMemorySize)
NVN_STUB(nvnCommandBufferGetCommandMemoryUsed)
NVN_STUB(nvnCommandBufferGetControlMemoryFree)
NVN_STUB(nvnCommandBufferGetControlMemorySize)
NVN_STUB(nvnCommandBufferGetControlMemoryUsed)
NVN_STUB(nvnCommandBufferGetCopyImageStride)
NVN_STUB(nvnCommandBufferGetCopyRowStride)
NVN_STUB(nvnCommandBufferGetMemoryCallback)
NVN_STUB(nvnCommandBufferGetMemoryCallbackData)
NVN_STUB(nvnCommandBufferInitialize)
NVN_STUB(nvnCommandBufferInsertDebugMarker)
NVN_STUB(nvnCommandBufferIsRecording)
NVN_STUB(nvnCommandBufferMultiDrawArraysIndirectCount)
NVN_STUB(nvnCommandBufferMultiDrawElementsIndirectCount)
NVN_STUB(nvnCommandBufferPauseTransformFeedback)
NVN_STUB(nvnCommandBufferPopDebugGroup)
NVN_STUB(nvnCommandBufferPushDebugGroup)
NVN_STUB(nvnCommandBufferReportCounter)
NVN_STUB(nvnCommandBufferReportValue)
NVN_STUB(nvnCommandBufferResetCounter)
NVN_STUB(nvnCommandBufferResolveDepthBuffer)
NVN_STUB(nvnCommandBufferRestoreZCullData)
NVN_STUB(nvnCommandBufferResumeTransformFeedback)
NVN_STUB(nvnCommandBufferSaveZCullData)
NVN_STUB(nvnCommandBufferSetAlphaRef)
NVN_STUB(nvnCommandBufferSetBlendColor)
NVN_STUB(nvnCommandBufferSetConservativeRasterDilate)
NVN_STUB(nvnCommandBufferSetConservativeRasterEnable)
NVN_STUB(nvnCommandBufferSetCopyImageStride)
NVN_STUB(nvnCommandBufferSetCopyRowStride)
NVN_STUB(nvnCommandBufferSetDebugLabel)
NVN_STUB(nvnCommandBufferSetDepthBounds)
NVN_STUB(nvnCommandBufferSetDepthClamp)
NVN_STUB(nvnCommandBufferSetDepthRange)
NVN_STUB(nvnCommandBufferSetDepthRanges)
NVN_STUB(nvnCommandBufferSetInnerTessellationLevels)
NVN_STUB(nvnCommandBufferSetLineWidth)
NVN_STUB(nvnCommandBufferSetMemoryCallback)
NVN_STUB(nvnCommandBufferSetMemoryCallbackData)
NVN_STUB(nvnCommandBufferSetOuterTessellationLevels)
NVN_STUB(nvnCommandBufferSetPatchSize)
NVN_STUB(nvnCommandBufferSetPointSize)
NVN_STUB(nvnCommandBufferSetPolygonOffsetClamp)
NVN_STUB(nvnCommandBufferSetPrimitiveRestart)
NVN_STUB(nvnCommandBufferSetProgramSubroutines)
NVN_STUB(nvnCommandBufferSetRasterizerDiscard)
NVN_STUB(nvnCommandBufferSetRenderEnable)
NVN_STUB(nvnCommandBufferSetRenderEnableConditional)
NVN_STUB(nvnCommandBufferSetRenderTargets)
NVN_STUB(nvnCommandBufferSetSampleMask)
NVN_STUB(nvnCommandBufferSetSamplerPool)
NVN_STUB(nvnCommandBufferSetScissor)
NVN_STUB(nvnCommandBufferSetScissors)
NVN_STUB(nvnCommandBufferSetShaderScratchMemory)
NVN_STUB(nvnCommandBufferSetStencilMask)
NVN_STUB(nvnCommandBufferSetStencilRef)
NVN_STUB(nvnCommandBufferSetStencilValueMask)
NVN_STUB(nvnCommandBufferSetSubpixelPrecisionBias)
NVN_STUB(nvnCommandBufferSetTexturePool)
NVN_STUB(nvnCommandBufferSetTiledCacheAction)
NVN_STUB(nvnCommandBufferSetTiledCacheTileSize)
NVN_STUB(nvnCommandBufferSetViewport)
NVN_STUB(nvnCommandBufferSetViewportSwizzles)
NVN_STUB(nvnCommandBufferSetViewports)
NVN_STUB(nvnCommandBufferTiledDownsample)
NVN_STUB(nvnCommandBufferUpdateUniformBuffer)
NVN_STUB(nvnCommandBufferWaitSync)
NVN_STUB(nvnDepthStencilStateGetDepthFunc)
NVN_STUB(nvnDepthStencilStateGetDepthTestEnable)
NVN_STUB(nvnDepthStencilStateGetDepthWriteEnable)
NVN_STUB(nvnDepthStencilStateGetStencilFunc)
NVN_STUB(nvnDepthStencilStateGetStencilOp)
NVN_STUB(nvnDepthStencilStateGetStencilTestEnable)
NVN_STUB(nvnDepthStencilStateSetDefaults)
NVN_STUB(nvnDepthStencilStateSetDepthFunc)
NVN_STUB(nvnDepthStencilStateSetDepthTestEnable)
NVN_STUB(nvnDepthStencilStateSetDepthWriteEnable)
NVN_STUB(nvnDepthStencilStateSetStencilFunc)
NVN_STUB(nvnDepthStencilStateSetStencilOp)
NVN_STUB(nvnDepthStencilStateSetStencilTestEnable)
NVN_STUB(nvnDeviceApplyDeferredFinalizes)
NVN_STUB(nvnDeviceFinalize)
NVN_STUB(nvnDeviceFinalizeCommandHandle)
NVN_STUB(nvnDeviceGetCurrentTimestampInNanoseconds)
NVN_STUB(nvnDeviceGetDepthMode)
NVN_STUB(nvnDeviceGetImageHandle)
NVN_STUB(nvnDeviceGetTexelFetchHandle)
NVN_STUB(nvnDeviceGetTextureHandle)
NVN_STUB(nvnDeviceGetTimestampInNanoseconds)
NVN_STUB(nvnDeviceGetWindowOriginMode)
NVN_STUB(nvnDeviceInstallDebugCallback)
NVN_STUB(nvnDeviceRegisterFastClearColor)
NVN_STUB(nvnDeviceRegisterFastClearColori)
NVN_STUB(nvnDeviceRegisterFastClearColorui)
NVN_STUB(nvnDeviceRegisterFastClearDepth)
NVN_STUB(nvnDeviceSetDebugLabel)
NVN_STUB(nvnDeviceSetDepthMode)
NVN_STUB(nvnDeviceSetIntermediateShaderCache)
NVN_STUB(nvnDeviceWaitForError)
NVN_STUB(nvnMemoryPoolBuilderGetFlags)
NVN_STUB(nvnMemoryPoolBuilderGetMemory)
NVN_STUB(nvnMemoryPoolBuilderGetSize)
NVN_STUB(nvnMemoryPoolFinalize)
NVN_STUB(nvnMemoryPoolFlushMappedRange)
NVN_STUB(nvnMemoryPoolGetBufferAddress)
NVN_STUB(nvnMemoryPoolGetFlags)
NVN_STUB(nvnMemoryPoolGetSize)
NVN_STUB(nvnMemoryPoolInvalidateMappedRange)
NVN_STUB(nvnMemoryPoolMap)
NVN_STUB(nvnMemoryPoolMapVirtual)
NVN_STUB(nvnMemoryPoolSetDebugLabel)
NVN_STUB(nvnMultisampleStateGetAlphaToCoverageDither)
NVN_STUB(nvnMultisampleStateGetAlphaToCoverageEnable)
NVN_STUB(nvnMultisampleStateGetCoverageModulationMode)
NVN_STUB(nvnMultisampleStateGetCoverageToColorEnable)
NVN_STUB(nvnMultisampleStateGetCoverageToColorOutput)
NVN_STUB(nvnMultisampleStateGetMultisampleEnable)
NVN_STUB(nvnMultisampleStateGetRasterSamples)
NVN_STUB(nvnMultisampleStateGetSampleLocationsEnable)
NVN_STUB(nvnMultisampleStateGetSampleLocationsGrid)
NVN_STUB(nvnMultisampleStateGetSampleLocationsGridEnable)
NVN_STUB(nvnMultisampleStateGetSamples)
NVN_STUB(nvnMultisampleStateSetAlphaToCoverageDither)
NVN_STUB(nvnMultisampleStateSetAlphaToCoverageEnable)
NVN_STUB(nvnMultisampleStateSetCoverageModulationMode)
NVN_STUB(nvnMultisampleStateSetCoverageToColorEnable)
NVN_STUB(nvnMultisampleStateSetCoverageToColorOutput)
NVN_STUB(nvnMultisampleStateSetDefaults)
NVN_STUB(nvnMultisampleStateSetMultisampleEnable)
NVN_STUB(nvnMultisampleStateSetRasterSamples)
NVN_STUB(nvnMultisampleStateSetSampleLocations)
NVN_STUB(nvnMultisampleStateSetSampleLocationsEnable)
NVN_STUB(nvnMultisampleStateSetSampleLocationsGridEnable)
NVN_STUB(nvnMultisampleStateSetSamples)
NVN_STUB(nvnPolygonStateGetCullFace)
NVN_STUB(nvnPolygonStateGetFrontFace)
NVN_STUB(nvnPolygonStateGetPolygonMode)
NVN_STUB(nvnPolygonStateGetPolygonOffsetEnables)
NVN_STUB(nvnPolygonStateSetCullFace)
NVN_STUB(nvnPolygonStateSetDefaults)
NVN_STUB(nvnPolygonStateSetFrontFace)
NVN_STUB(nvnPolygonStateSetPolygonMode)
NVN_STUB(nvnPolygonStateSetPolygonOffsetEnables)
NVN_STUB(nvnProgramFinalize)
NVN_STUB(nvnProgramInitialize)
NVN_STUB(nvnProgramSetDebugLabel)
NVN_STUB(nvnProgramSetShaders)
NVN_STUB(nvnProgramSetSubroutineLinkage)
NVN_STUB(nvnQueueAcquireTexture)
NVN_STUB(nvnQueueBuilderGetQueueMemorySize)
NVN_STUB(nvnQueueBuilderSetCommandFlushThreshold)
NVN_STUB(nvnQueueBuilderSetCommandMemorySize)
NVN_STUB(nvnQueueBuilderSetComputeMemorySize)
NVN_STUB(nvnQueueBuilderSetControlMemorySize)
NVN_STUB(nvnQueueBuilderSetDefaults)
NVN_STUB(nvnQueueBuilderSetDevice)
NVN_STUB(nvnQueueBuilderSetFlags)
NVN_STUB(nvnQueueBuilderSetQueueMemory)
NVN_STUB(nvnQueueFenceSync)
NVN_STUB(nvnQueueFinalize)
NVN_STUB(nvnQueueFinish)
NVN_STUB(nvnQueueFlush)
NVN_STUB(nvnQueueGetError)
NVN_STUB(nvnQueueGetTotalCommandMemoryUsed)
NVN_STUB(nvnQueueGetTotalComputeMemoryUsed)
NVN_STUB(nvnQueueGetTotalControlMemoryUsed)
NVN_STUB(nvnQueueInitialize)
NVN_STUB(nvnQueuePresentTexture)
NVN_STUB(nvnQueueResetMemoryUsageCounts)
NVN_STUB(nvnQueueSetDebugLabel)
NVN_STUB(nvnQueueSubmitCommands)
NVN_STUB(nvnQueueWaitSync)
NVN_STUB(nvnSamplerBuilderGetBorderColor)
NVN_STUB(nvnSamplerBuilderGetBorderColori)
NVN_STUB(nvnSamplerBuilderGetBorderColorui)
NVN_STUB(nvnSamplerBuilderGetCompare)
NVN_STUB(nvnSamplerBuilderGetLodBias)
NVN_STUB(nvnSamplerBuilderGetLodClamp)
NVN_STUB(nvnSamplerBuilderGetMaxAnisotropy)
NVN_STUB(nvnSamplerBuilderGetMinMagFilter)
NVN_STUB(nvnSamplerBuilderGetReductionFilter)
NVN_STUB(nvnSamplerBuilderGetWrapMode)
NVN_STUB(nvnSamplerBuilderSetBorderColor)
NVN_STUB(nvnSamplerBuilderSetBorderColori)
NVN_STUB(nvnSamplerBuilderSetBorderColorui)
NVN_STUB(nvnSamplerBuilderSetCompare)
NVN_STUB(nvnSamplerBuilderSetDefaults)
NVN_STUB(nvnSamplerBuilderSetDevice)
NVN_STUB(nvnSamplerBuilderSetLodBias)
NVN_STUB(nvnSamplerBuilderSetLodClamp)
NVN_STUB(nvnSamplerBuilderSetMaxAnisotropy)
NVN_STUB(nvnSamplerBuilderSetMinMagFilter)
NVN_STUB(nvnSamplerBuilderSetReductionFilter)
NVN_STUB(nvnSamplerBuilderSetWrapMode)
NVN_STUB(nvnSamplerCompare)
NVN_STUB(nvnSamplerFinalize)
NVN_STUB(nvnSamplerGetBorderColor)
NVN_STUB(nvnSamplerGetBorderColori)
NVN_STUB(nvnSamplerGetBorderColorui)
NVN_STUB(nvnSamplerGetCompare)
NVN_STUB(nvnSamplerGetDebugID)
NVN_STUB(nvnSamplerGetLodBias)
NVN_STUB(nvnSamplerGetLodClamp)
NVN_STUB(nvnSamplerGetMaxAnisotropy)
NVN_STUB(nvnSamplerGetMinMagFilter)
NVN_STUB(nvnSamplerGetReductionFilter)
NVN_STUB(nvnSamplerGetWrapMode)
NVN_STUB(nvnSamplerInitialize)
NVN_STUB(nvnSamplerPoolFinalize)
NVN_STUB(nvnSamplerPoolGetMemoryOffset)
NVN_STUB(nvnSamplerPoolGetMemoryPool)
NVN_STUB(nvnSamplerPoolGetSize)
NVN_STUB(nvnSamplerPoolInitialize)
NVN_STUB(nvnSamplerPoolRegisterSampler)
NVN_STUB(nvnSamplerPoolSetDebugLabel)
NVN_STUB(nvnSamplerSetDebugLabel)
NVN_STUB(nvnSyncFinalize)
NVN_STUB(nvnSyncInitialize)
NVN_STUB(nvnSyncSetDebugLabel)
NVN_STUB(nvnSyncWait)
NVN_STUB(nvnTextureBuilderGetDepth)
NVN_STUB(nvnTextureBuilderGetDepthStencilMode)
NVN_STUB(nvnTextureBuilderGetFlags)
NVN_STUB(nvnTextureBuilderGetFormat)
NVN_STUB(nvnTextureBuilderGetGLTextureName)
NVN_STUB(nvnTextureBuilderGetHeight)
NVN_STUB(nvnTextureBuilderGetLevels)
NVN_STUB(nvnTextureBuilderGetMemoryOffset)
NVN_STUB(nvnTextureBuilderGetMemoryPool)
NVN_STUB(nvnTextureBuilderGetPackagedTextureData)
NVN_STUB(nvnTextureBuilderGetSamples)
NVN_STUB(nvnTextureBuilderGetSparseTileLayout)
NVN_STUB(nvnTextureBuilderGetStorageAlignment)
NVN_STUB(nvnTextureBuilderGetStorageClass)
NVN_STUB(nvnTextureBuilderGetStorageSize)
NVN_STUB(nvnTextureBuilderGetStride)
NVN_STUB(nvnTextureBuilderGetSwizzle)
NVN_STUB(nvnTextureBuilderGetTarget)
NVN_STUB(nvnTextureBuilderGetWidth)
NVN_STUB(nvnTextureBuilderGetZCullStorageSize)
NVN_STUB(nvnTextureBuilderSetDefaults)
NVN_STUB(nvnTextureBuilderSetDepth)
NVN_STUB(nvnTextureBuilderSetDepthStencilMode)
NVN_STUB(nvnTextureBuilderSetDevice)
NVN_STUB(nvnTextureBuilderSetFlags)
NVN_STUB(nvnTextureBuilderSetFormat)
NVN_STUB(nvnTextureBuilderSetGLTextureName)
NVN_STUB(nvnTextureBuilderSetHeight)
NVN_STUB(nvnTextureBuilderSetLevels)
NVN_STUB(nvnTextureBuilderSetPackagedTextureData)
NVN_STUB(nvnTextureBuilderSetPackagedTextureLayout)
NVN_STUB(nvnTextureBuilderSetSamples)
NVN_STUB(nvnTextureBuilderSetSize1D)
NVN_STUB(nvnTextureBuilderSetSize2D)
NVN_STUB(nvnTextureBuilderSetSize3D)
NVN_STUB(nvnTextureBuilderSetStorage)
NVN_STUB(nvnTextureBuilderSetStride)
NVN_STUB(nvnTextureBuilderSetSwizzle)
NVN_STUB(nvnTextureBuilderSetTarget)
NVN_STUB(nvnTextureBuilderSetWidth)
NVN_STUB(nvnTextureCompare)
NVN_STUB(nvnTextureFinalize)
NVN_STUB(nvnTextureFlushTexels)
NVN_STUB(nvnTextureGetDebugID)
NVN_STUB(nvnTextureGetDepth)
NVN_STUB(nvnTextureGetDepthStencilMode)
NVN_STUB(nvnTextureGetFlags)
NVN_STUB(nvnTextureGetFormat)
NVN_STUB(nvnTextureGetHeight)
NVN_STUB(nvnTextureGetLevels)
NVN_STUB(nvnTextureGetMemoryOffset)
NVN_STUB(nvnTextureGetMemoryPool)
NVN_STUB(nvnTextureGetSamples)
NVN_STUB(nvnTextureGetSparseTileLayout)
NVN_STUB(nvnTextureGetStorageClass)
NVN_STUB(nvnTextureGetStorageSize)
NVN_STUB(nvnTextureGetStride)
NVN_STUB(nvnTextureGetSwizzle)
NVN_STUB(nvnTextureGetTarget)
NVN_STUB(nvnTextureGetTextureAddress)
NVN_STUB(nvnTextureGetViewOffset)
NVN_STUB(nvnTextureGetWidth)
NVN_STUB(nvnTextureGetZCullStorageSize)
NVN_STUB(nvnTextureInitialize)
NVN_STUB(nvnTextureInvalidateTexels)
NVN_STUB(nvnTexturePoolFinalize)
NVN_STUB(nvnTexturePoolGetMemoryOffset)
NVN_STUB(nvnTexturePoolGetMemoryPool)
NVN_STUB(nvnTexturePoolGetSize)
NVN_STUB(nvnTexturePoolInitialize)
NVN_STUB(nvnTexturePoolRegisterImage)
NVN_STUB(nvnTexturePoolRegisterTexture)
NVN_STUB(nvnTexturePoolSetDebugLabel)
NVN_STUB(nvnTextureReadTexels)
NVN_STUB(nvnTextureSetDebugLabel)
NVN_STUB(nvnTextureViewCompare)
NVN_STUB(nvnTextureViewGetDepthStencilMode)
NVN_STUB(nvnTextureViewGetFormat)
NVN_STUB(nvnTextureViewGetLayers)
NVN_STUB(nvnTextureViewGetLevels)
NVN_STUB(nvnTextureViewGetSwizzle)
NVN_STUB(nvnTextureViewGetTarget)
NVN_STUB(nvnTextureViewSetDefaults)
NVN_STUB(nvnTextureViewSetDepthStencilMode)
NVN_STUB(nvnTextureViewSetFormat)
NVN_STUB(nvnTextureViewSetLayers)
NVN_STUB(nvnTextureViewSetLevels)
NVN_STUB(nvnTextureViewSetSwizzle)
NVN_STUB(nvnTextureViewSetTarget)
NVN_STUB(nvnTextureWriteTexels)
NVN_STUB(nvnVertexAttribStateGetFormat)
NVN_STUB(nvnVertexAttribStateGetStreamIndex)
NVN_STUB(nvnVertexAttribStateSetDefaults)
NVN_STUB(nvnVertexAttribStateSetFormat)
NVN_STUB(nvnVertexAttribStateSetStreamIndex)
NVN_STUB(nvnVertexStreamStateGetDivisor)
NVN_STUB(nvnVertexStreamStateGetStride)
NVN_STUB(nvnVertexStreamStateSetDefaults)
NVN_STUB(nvnVertexStreamStateSetDivisor)
NVN_STUB(nvnVertexStreamStateSetStride)
NVN_STUB(nvnWindowAcquireTexture)
NVN_STUB(nvnWindowBuilderGetNativeWindow)
NVN_STUB(nvnWindowBuilderGetPresentInterval)
NVN_STUB(nvnWindowBuilderSetDefaults)
NVN_STUB(nvnWindowBuilderSetDevice)
NVN_STUB(nvnWindowBuilderSetNativeWindow)
NVN_STUB(nvnWindowBuilderSetPresentInterval)
NVN_STUB(nvnWindowBuilderSetTextures)
NVN_STUB(nvnWindowFinalize)
NVN_STUB(nvnWindowGetNativeWindow)
NVN_STUB(nvnWindowGetPresentInterval)
NVN_STUB(nvnWindowInitialize)
NVN_STUB(nvnWindowSetCrop)
NVN_STUB(nvnWindowSetDebugLabel)
NVN_STUB(nvnWindowSetPresentInterval)

#define NVN_FUNC(fname) if(strcmp(name, #fname) == 0) return reinterpret_cast<void*>(fname);

void* nvnDeviceGetProcAddress(const uint64_t unk, const char* name) {
    std::cout << "nvnDeviceGetProcAddress called! (" << unk << ") '" << name << "'" << std::endl;
    NVN_ALL(NVN_FUNC);
    if(strcmp(name, "nvnDeviceGetProcAddress") == 0) return reinterpret_cast<void*>(nvnDeviceGetProcAddress);
    std::cout << "Could not find nvn function " << name << std::endl;
    __builtin_trap();
    return nullptr;
}

void* nvnBootstrapLoader(const char* name) {
    std::cout << "nvnBootstrapLoader called! '" << name << "'" << std::endl;
    if(strcmp(name, "nvnDeviceGetProcAddress") == 0)
        return reinterpret_cast<void*>(nvnDeviceGetProcAddress);
    return nullptr;
}
