#ifndef NATIVELIB_NVN_H
#define NATIVELIB_NVN_H

#define NVN_ALL(with) \
with(nvnBlendStateGetAdvancedMode) \
with(nvnBlendStateGetAdvancedNormalizedDst) \
with(nvnBlendStateGetAdvancedOverlap) \
with(nvnBlendStateGetAdvancedPremultipliedSrc) \
with(nvnBlendStateGetBlendEquation) \
with(nvnBlendStateGetBlendFunc) \
with(nvnBlendStateGetBlendTarget) \
with(nvnBlendStateSetAdvancedMode) \
with(nvnBlendStateSetAdvancedNormalizedDst) \
with(nvnBlendStateSetAdvancedOverlap) \
with(nvnBlendStateSetAdvancedPremultipliedSrc) \
with(nvnBlendStateSetBlendEquation) \
with(nvnBlendStateSetBlendFunc) \
with(nvnBlendStateSetBlendTarget) \
with(nvnBlendStateSetDefaults) \
with(nvnBufferBuilderGetMemoryOffset) \
with(nvnBufferBuilderGetMemoryPool) \
with(nvnBufferBuilderGetSize) \
with(nvnBufferBuilderSetDefaults) \
with(nvnBufferBuilderSetDevice) \
with(nvnBufferBuilderSetStorage) \
with(nvnBufferFinalize) \
with(nvnBufferFlushMappedRange) \
with(nvnBufferGetAddress) \
with(nvnBufferGetDebugID) \
with(nvnBufferGetMemoryOffset) \
with(nvnBufferGetMemoryPool) \
with(nvnBufferGetSize) \
with(nvnBufferInitialize) \
with(nvnBufferInvalidateMappedRange) \
with(nvnBufferMap) \
with(nvnBufferSetDebugLabel) \
with(nvnChannelMaskStateGetChannelMask) \
with(nvnChannelMaskStateSetChannelMask) \
with(nvnChannelMaskStateSetDefaults) \
with(nvnColorStateGetAlphaTest) \
with(nvnColorStateGetBlendEnable) \
with(nvnColorStateGetLogicOp) \
with(nvnColorStateSetAlphaTest) \
with(nvnColorStateSetBlendEnable) \
with(nvnColorStateSetDefaults) \
with(nvnColorStateSetLogicOp) \
with(nvnCommandBufferAddCommandMemory) \
with(nvnCommandBufferAddControlMemory) \
with(nvnCommandBufferBarrier) \
with(nvnCommandBufferBeginRecording) \
with(nvnCommandBufferBeginTransformFeedback) \
with(nvnCommandBufferBindBlendState) \
with(nvnCommandBufferBindChannelMaskState) \
with(nvnCommandBufferBindColorState) \
with(nvnCommandBufferBindCoverageModulationTable) \
with(nvnCommandBufferBindDepthStencilState) \
with(nvnCommandBufferBindImage) \
with(nvnCommandBufferBindImages) \
with(nvnCommandBufferBindMultisampleState) \
with(nvnCommandBufferBindPolygonState) \
with(nvnCommandBufferBindProgram) \
with(nvnCommandBufferBindStorageBuffer) \
with(nvnCommandBufferBindStorageBuffers) \
with(nvnCommandBufferBindTexture) \
with(nvnCommandBufferBindTextures) \
with(nvnCommandBufferBindTransformFeedbackBuffer) \
with(nvnCommandBufferBindTransformFeedbackBuffers) \
with(nvnCommandBufferBindUniformBuffer) \
with(nvnCommandBufferBindUniformBuffers) \
with(nvnCommandBufferBindVertexAttribState) \
with(nvnCommandBufferBindVertexBuffer) \
with(nvnCommandBufferBindVertexBuffers) \
with(nvnCommandBufferBindVertexStreamState) \
with(nvnCommandBufferCallCommands) \
with(nvnCommandBufferClearBuffer) \
with(nvnCommandBufferClearColor) \
with(nvnCommandBufferClearColori) \
with(nvnCommandBufferClearColorui) \
with(nvnCommandBufferClearDepthStencil) \
with(nvnCommandBufferClearTexture) \
with(nvnCommandBufferClearTexturei) \
with(nvnCommandBufferClearTextureui) \
with(nvnCommandBufferCopyBufferToBuffer) \
with(nvnCommandBufferCopyBufferToTexture) \
with(nvnCommandBufferCopyCommands) \
with(nvnCommandBufferCopyTextureToBuffer) \
with(nvnCommandBufferCopyTextureToTexture) \
with(nvnCommandBufferDiscardColor) \
with(nvnCommandBufferDiscardDepthStencil) \
with(nvnCommandBufferDispatchCompute) \
with(nvnCommandBufferDispatchComputeIndirect) \
with(nvnCommandBufferDownsample) \
with(nvnCommandBufferDrawArrays) \
with(nvnCommandBufferDrawArraysIndirect) \
with(nvnCommandBufferDrawArraysInstanced) \
with(nvnCommandBufferDrawElements) \
with(nvnCommandBufferDrawElementsBaseVertex) \
with(nvnCommandBufferDrawElementsIndirect) \
with(nvnCommandBufferDrawElementsInstanced) \
with(nvnCommandBufferDrawTexture) \
with(nvnCommandBufferDrawTransformFeedback) \
with(nvnCommandBufferEndRecording) \
with(nvnCommandBufferEndTransformFeedback) \
with(nvnCommandBufferFenceSync) \
with(nvnCommandBufferFinalize) \
with(nvnCommandBufferGetCommandMemoryFree) \
with(nvnCommandBufferGetCommandMemorySize) \
with(nvnCommandBufferGetCommandMemoryUsed) \
with(nvnCommandBufferGetControlMemoryFree) \
with(nvnCommandBufferGetControlMemorySize) \
with(nvnCommandBufferGetControlMemoryUsed) \
with(nvnCommandBufferGetCopyImageStride) \
with(nvnCommandBufferGetCopyRowStride) \
with(nvnCommandBufferGetMemoryCallback) \
with(nvnCommandBufferGetMemoryCallbackData) \
with(nvnCommandBufferInitialize) \
with(nvnCommandBufferInsertDebugMarker) \
with(nvnCommandBufferIsRecording) \
with(nvnCommandBufferMultiDrawArraysIndirectCount) \
with(nvnCommandBufferMultiDrawElementsIndirectCount) \
with(nvnCommandBufferPauseTransformFeedback) \
with(nvnCommandBufferPopDebugGroup) \
with(nvnCommandBufferPushDebugGroup) \
with(nvnCommandBufferReportCounter) \
with(nvnCommandBufferReportValue) \
with(nvnCommandBufferResetCounter) \
with(nvnCommandBufferResolveDepthBuffer) \
with(nvnCommandBufferRestoreZCullData) \
with(nvnCommandBufferResumeTransformFeedback) \
with(nvnCommandBufferSaveZCullData) \
with(nvnCommandBufferSetAlphaRef) \
with(nvnCommandBufferSetBlendColor) \
with(nvnCommandBufferSetConservativeRasterDilate) \
with(nvnCommandBufferSetConservativeRasterEnable) \
with(nvnCommandBufferSetCopyImageStride) \
with(nvnCommandBufferSetCopyRowStride) \
with(nvnCommandBufferSetDebugLabel) \
with(nvnCommandBufferSetDepthBounds) \
with(nvnCommandBufferSetDepthClamp) \
with(nvnCommandBufferSetDepthRange) \
with(nvnCommandBufferSetDepthRanges) \
with(nvnCommandBufferSetInnerTessellationLevels) \
with(nvnCommandBufferSetLineWidth) \
with(nvnCommandBufferSetMemoryCallback) \
with(nvnCommandBufferSetMemoryCallbackData) \
with(nvnCommandBufferSetOuterTessellationLevels) \
with(nvnCommandBufferSetPatchSize) \
with(nvnCommandBufferSetPointSize) \
with(nvnCommandBufferSetPolygonOffsetClamp) \
with(nvnCommandBufferSetPrimitiveRestart) \
with(nvnCommandBufferSetProgramSubroutines) \
with(nvnCommandBufferSetRasterizerDiscard) \
with(nvnCommandBufferSetRenderEnable) \
with(nvnCommandBufferSetRenderEnableConditional) \
with(nvnCommandBufferSetRenderTargets) \
with(nvnCommandBufferSetSampleMask) \
with(nvnCommandBufferSetSamplerPool) \
with(nvnCommandBufferSetScissor) \
with(nvnCommandBufferSetScissors) \
with(nvnCommandBufferSetShaderScratchMemory) \
with(nvnCommandBufferSetStencilMask) \
with(nvnCommandBufferSetStencilRef) \
with(nvnCommandBufferSetStencilValueMask) \
with(nvnCommandBufferSetSubpixelPrecisionBias) \
with(nvnCommandBufferSetTexturePool) \
with(nvnCommandBufferSetTiledCacheAction) \
with(nvnCommandBufferSetTiledCacheTileSize) \
with(nvnCommandBufferSetViewport) \
with(nvnCommandBufferSetViewportSwizzles) \
with(nvnCommandBufferSetViewports) \
with(nvnCommandBufferTiledDownsample) \
with(nvnCommandBufferUpdateUniformBuffer) \
with(nvnCommandBufferWaitSync) \
with(nvnDepthStencilStateGetDepthFunc) \
with(nvnDepthStencilStateGetDepthTestEnable) \
with(nvnDepthStencilStateGetDepthWriteEnable) \
with(nvnDepthStencilStateGetStencilFunc) \
with(nvnDepthStencilStateGetStencilOp) \
with(nvnDepthStencilStateGetStencilTestEnable) \
with(nvnDepthStencilStateSetDefaults) \
with(nvnDepthStencilStateSetDepthFunc) \
with(nvnDepthStencilStateSetDepthTestEnable) \
with(nvnDepthStencilStateSetDepthWriteEnable) \
with(nvnDepthStencilStateSetStencilFunc) \
with(nvnDepthStencilStateSetStencilOp) \
with(nvnDepthStencilStateSetStencilTestEnable) \
with(nvnDeviceApplyDeferredFinalizes) \
with(nvnDeviceBuilderSetDefaults) \
with(nvnDeviceBuilderSetFlags) \
with(nvnDeviceFinalize) \
with(nvnDeviceFinalizeCommandHandle) \
with(nvnDeviceGetCurrentTimestampInNanoseconds) \
with(nvnDeviceGetDepthMode) \
with(nvnDeviceGetImageHandle) \
with(nvnDeviceGetInteger) \
with(nvnDeviceGetTexelFetchHandle) \
with(nvnDeviceGetTextureHandle) \
with(nvnDeviceGetTimestampInNanoseconds) \
with(nvnDeviceGetWindowOriginMode) \
with(nvnDeviceInitialize) \
with(nvnDeviceInstallDebugCallback) \
with(nvnDeviceRegisterFastClearColor) \
with(nvnDeviceRegisterFastClearColori) \
with(nvnDeviceRegisterFastClearColorui) \
with(nvnDeviceRegisterFastClearDepth) \
with(nvnDeviceSetDebugLabel) \
with(nvnDeviceSetDepthMode) \
with(nvnDeviceSetIntermediateShaderCache) \
with(nvnDeviceSetWindowOriginMode) \
with(nvnDeviceWaitForError) \
with(nvnMemoryPoolBuilderGetFlags) \
with(nvnMemoryPoolBuilderGetMemory) \
with(nvnMemoryPoolBuilderGetSize) \
with(nvnMemoryPoolBuilderSetDefaults) \
with(nvnMemoryPoolBuilderSetDevice) \
with(nvnMemoryPoolBuilderSetFlags) \
with(nvnMemoryPoolBuilderSetStorage) \
with(nvnMemoryPoolFinalize) \
with(nvnMemoryPoolFlushMappedRange) \
with(nvnMemoryPoolGetBufferAddress) \
with(nvnMemoryPoolGetFlags) \
with(nvnMemoryPoolGetSize) \
with(nvnMemoryPoolInitialize) \
with(nvnMemoryPoolInvalidateMappedRange) \
with(nvnMemoryPoolMap) \
with(nvnMemoryPoolMapVirtual) \
with(nvnMemoryPoolSetDebugLabel) \
with(nvnMultisampleStateGetAlphaToCoverageDither) \
with(nvnMultisampleStateGetAlphaToCoverageEnable) \
with(nvnMultisampleStateGetCoverageModulationMode) \
with(nvnMultisampleStateGetCoverageToColorEnable) \
with(nvnMultisampleStateGetCoverageToColorOutput) \
with(nvnMultisampleStateGetMultisampleEnable) \
with(nvnMultisampleStateGetRasterSamples) \
with(nvnMultisampleStateGetSampleLocationsEnable) \
with(nvnMultisampleStateGetSampleLocationsGrid) \
with(nvnMultisampleStateGetSampleLocationsGridEnable) \
with(nvnMultisampleStateGetSamples) \
with(nvnMultisampleStateSetAlphaToCoverageDither) \
with(nvnMultisampleStateSetAlphaToCoverageEnable) \
with(nvnMultisampleStateSetCoverageModulationMode) \
with(nvnMultisampleStateSetCoverageToColorEnable) \
with(nvnMultisampleStateSetCoverageToColorOutput) \
with(nvnMultisampleStateSetDefaults) \
with(nvnMultisampleStateSetMultisampleEnable) \
with(nvnMultisampleStateSetRasterSamples) \
with(nvnMultisampleStateSetSampleLocations) \
with(nvnMultisampleStateSetSampleLocationsEnable) \
with(nvnMultisampleStateSetSampleLocationsGridEnable) \
with(nvnMultisampleStateSetSamples) \
with(nvnPolygonStateGetCullFace) \
with(nvnPolygonStateGetFrontFace) \
with(nvnPolygonStateGetPolygonMode) \
with(nvnPolygonStateGetPolygonOffsetEnables) \
with(nvnPolygonStateSetCullFace) \
with(nvnPolygonStateSetDefaults) \
with(nvnPolygonStateSetFrontFace) \
with(nvnPolygonStateSetPolygonMode) \
with(nvnPolygonStateSetPolygonOffsetEnables) \
with(nvnProgramFinalize) \
with(nvnProgramInitialize) \
with(nvnProgramSetDebugLabel) \
with(nvnProgramSetShaders) \
with(nvnProgramSetSubroutineLinkage) \
with(nvnQueueAcquireTexture) \
with(nvnQueueBuilderGetQueueMemorySize) \
with(nvnQueueBuilderSetCommandFlushThreshold) \
with(nvnQueueBuilderSetCommandMemorySize) \
with(nvnQueueBuilderSetComputeMemorySize) \
with(nvnQueueBuilderSetControlMemorySize) \
with(nvnQueueBuilderSetDefaults) \
with(nvnQueueBuilderSetDevice) \
with(nvnQueueBuilderSetFlags) \
with(nvnQueueBuilderSetQueueMemory) \
with(nvnQueueFenceSync) \
with(nvnQueueFinalize) \
with(nvnQueueFinish) \
with(nvnQueueFlush) \
with(nvnQueueGetError) \
with(nvnQueueGetTotalCommandMemoryUsed) \
with(nvnQueueGetTotalComputeMemoryUsed) \
with(nvnQueueGetTotalControlMemoryUsed) \
with(nvnQueueInitialize) \
with(nvnQueuePresentTexture) \
with(nvnQueueResetMemoryUsageCounts) \
with(nvnQueueSetDebugLabel) \
with(nvnQueueSubmitCommands) \
with(nvnQueueWaitSync) \
with(nvnSamplerBuilderGetBorderColor) \
with(nvnSamplerBuilderGetBorderColori) \
with(nvnSamplerBuilderGetBorderColorui) \
with(nvnSamplerBuilderGetCompare) \
with(nvnSamplerBuilderGetLodBias) \
with(nvnSamplerBuilderGetLodClamp) \
with(nvnSamplerBuilderGetMaxAnisotropy) \
with(nvnSamplerBuilderGetMinMagFilter) \
with(nvnSamplerBuilderGetReductionFilter) \
with(nvnSamplerBuilderGetWrapMode) \
with(nvnSamplerBuilderSetBorderColor) \
with(nvnSamplerBuilderSetBorderColori) \
with(nvnSamplerBuilderSetBorderColorui) \
with(nvnSamplerBuilderSetCompare) \
with(nvnSamplerBuilderSetDefaults) \
with(nvnSamplerBuilderSetDevice) \
with(nvnSamplerBuilderSetLodBias) \
with(nvnSamplerBuilderSetLodClamp) \
with(nvnSamplerBuilderSetMaxAnisotropy) \
with(nvnSamplerBuilderSetMinMagFilter) \
with(nvnSamplerBuilderSetReductionFilter) \
with(nvnSamplerBuilderSetWrapMode) \
with(nvnSamplerCompare) \
with(nvnSamplerFinalize) \
with(nvnSamplerGetBorderColor) \
with(nvnSamplerGetBorderColori) \
with(nvnSamplerGetBorderColorui) \
with(nvnSamplerGetCompare) \
with(nvnSamplerGetDebugID) \
with(nvnSamplerGetLodBias) \
with(nvnSamplerGetLodClamp) \
with(nvnSamplerGetMaxAnisotropy) \
with(nvnSamplerGetMinMagFilter) \
with(nvnSamplerGetReductionFilter) \
with(nvnSamplerGetWrapMode) \
with(nvnSamplerInitialize) \
with(nvnSamplerPoolFinalize) \
with(nvnSamplerPoolGetMemoryOffset) \
with(nvnSamplerPoolGetMemoryPool) \
with(nvnSamplerPoolGetSize) \
with(nvnSamplerPoolInitialize) \
with(nvnSamplerPoolRegisterSampler) \
with(nvnSamplerPoolSetDebugLabel) \
with(nvnSamplerSetDebugLabel) \
with(nvnSyncFinalize) \
with(nvnSyncInitialize) \
with(nvnSyncSetDebugLabel) \
with(nvnSyncWait) \
with(nvnTextureBuilderGetDepth) \
with(nvnTextureBuilderGetDepthStencilMode) \
with(nvnTextureBuilderGetFlags) \
with(nvnTextureBuilderGetFormat) \
with(nvnTextureBuilderGetGLTextureName) \
with(nvnTextureBuilderGetHeight) \
with(nvnTextureBuilderGetLevels) \
with(nvnTextureBuilderGetMemoryOffset) \
with(nvnTextureBuilderGetMemoryPool) \
with(nvnTextureBuilderGetPackagedTextureData) \
with(nvnTextureBuilderGetSamples) \
with(nvnTextureBuilderGetSparseTileLayout) \
with(nvnTextureBuilderGetStorageAlignment) \
with(nvnTextureBuilderGetStorageClass) \
with(nvnTextureBuilderGetStorageSize) \
with(nvnTextureBuilderGetStride) \
with(nvnTextureBuilderGetSwizzle) \
with(nvnTextureBuilderGetTarget) \
with(nvnTextureBuilderGetWidth) \
with(nvnTextureBuilderGetZCullStorageSize) \
with(nvnTextureBuilderSetDefaults) \
with(nvnTextureBuilderSetDepth) \
with(nvnTextureBuilderSetDepthStencilMode) \
with(nvnTextureBuilderSetDevice) \
with(nvnTextureBuilderSetFlags) \
with(nvnTextureBuilderSetFormat) \
with(nvnTextureBuilderSetGLTextureName) \
with(nvnTextureBuilderSetHeight) \
with(nvnTextureBuilderSetLevels) \
with(nvnTextureBuilderSetPackagedTextureData) \
with(nvnTextureBuilderSetPackagedTextureLayout) \
with(nvnTextureBuilderSetSamples) \
with(nvnTextureBuilderSetSize1D) \
with(nvnTextureBuilderSetSize2D) \
with(nvnTextureBuilderSetSize3D) \
with(nvnTextureBuilderSetStorage) \
with(nvnTextureBuilderSetStride) \
with(nvnTextureBuilderSetSwizzle) \
with(nvnTextureBuilderSetTarget) \
with(nvnTextureBuilderSetWidth) \
with(nvnTextureCompare) \
with(nvnTextureFinalize) \
with(nvnTextureFlushTexels) \
with(nvnTextureGetDebugID) \
with(nvnTextureGetDepth) \
with(nvnTextureGetDepthStencilMode) \
with(nvnTextureGetFlags) \
with(nvnTextureGetFormat) \
with(nvnTextureGetHeight) \
with(nvnTextureGetLevels) \
with(nvnTextureGetMemoryOffset) \
with(nvnTextureGetMemoryPool) \
with(nvnTextureGetSamples) \
with(nvnTextureGetSparseTileLayout) \
with(nvnTextureGetStorageClass) \
with(nvnTextureGetStorageSize) \
with(nvnTextureGetStride) \
with(nvnTextureGetSwizzle) \
with(nvnTextureGetTarget) \
with(nvnTextureGetTextureAddress) \
with(nvnTextureGetViewOffset) \
with(nvnTextureGetWidth) \
with(nvnTextureGetZCullStorageSize) \
with(nvnTextureInitialize) \
with(nvnTextureInvalidateTexels) \
with(nvnTexturePoolFinalize) \
with(nvnTexturePoolGetMemoryOffset) \
with(nvnTexturePoolGetMemoryPool) \
with(nvnTexturePoolGetSize) \
with(nvnTexturePoolInitialize) \
with(nvnTexturePoolRegisterImage) \
with(nvnTexturePoolRegisterTexture) \
with(nvnTexturePoolSetDebugLabel) \
with(nvnTextureReadTexels) \
with(nvnTextureSetDebugLabel) \
with(nvnTextureViewCompare) \
with(nvnTextureViewGetDepthStencilMode) \
with(nvnTextureViewGetFormat) \
with(nvnTextureViewGetLayers) \
with(nvnTextureViewGetLevels) \
with(nvnTextureViewGetSwizzle) \
with(nvnTextureViewGetTarget) \
with(nvnTextureViewSetDefaults) \
with(nvnTextureViewSetDepthStencilMode) \
with(nvnTextureViewSetFormat) \
with(nvnTextureViewSetLayers) \
with(nvnTextureViewSetLevels) \
with(nvnTextureViewSetSwizzle) \
with(nvnTextureViewSetTarget) \
with(nvnTextureWriteTexels) \
with(nvnVertexAttribStateGetFormat) \
with(nvnVertexAttribStateGetStreamIndex) \
with(nvnVertexAttribStateSetDefaults) \
with(nvnVertexAttribStateSetFormat) \
with(nvnVertexAttribStateSetStreamIndex) \
with(nvnVertexStreamStateGetDivisor) \
with(nvnVertexStreamStateGetStride) \
with(nvnVertexStreamStateSetDefaults) \
with(nvnVertexStreamStateSetDivisor) \
with(nvnVertexStreamStateSetStride) \
with(nvnWindowAcquireTexture) \
with(nvnWindowBuilderGetNativeWindow) \
with(nvnWindowBuilderGetPresentInterval) \
with(nvnWindowBuilderSetDefaults) \
with(nvnWindowBuilderSetDevice) \
with(nvnWindowBuilderSetNativeWindow) \
with(nvnWindowBuilderSetPresentInterval) \
with(nvnWindowBuilderSetTextures) \
with(nvnWindowFinalize) \
with(nvnWindowGetNativeWindow) \
with(nvnWindowGetPresentInterval) \
with(nvnWindowInitialize) \
with(nvnWindowSetCrop) \
with(nvnWindowSetDebugLabel) \
with(nvnWindowSetPresentInterval)

#endif //NATIVELIB_NVN_H